### ISSUE TITLE
Display the name of promo code in the cart

### ISSUE THREAD

**Issue by judbd** [snipcart/snipcart-v3-feedback#10]
In V2, the name of promo code was displayed, it was very informative in the case of bulk discount or special event discount. Now there is just the amount, but no clue for the client on why he have an automatic discount.

**Comment by couellet** [comment]
We'll add a way to show which discounts are applied in the upcoming releases:

![image](https://user-images.githubusercontent.com/281353/58129046-8bcdfe80-7bde-11e9-9fd6-47273c0e5da0.png)

We'll show a kind of tooltip when people will click/hover the `?` sign.

**Comment by judbd** [comment]
Ok, it is more obvious now as the coupons/bulk discounts can be used form promotion and and advertising purpose, and an big discount showed in the cart can trigger the order.

It's more subtle and clean in the new version but it's less obvious for advertising and buying decisions.

**Comment by couellet** [comment]
We did lot of UX research for this new design / checkout flow and a thing we learned is that less distractions during checkout lead to better conversion flow.

However, you'll be able to customize these parts of the cart if needed ;)

**Comment by judbd** [comment]
Great thank you!

**Comment by pgmichael** [comment]
Hi @judbd,
As discussed by @couellet, the `?` sign solution is now available in the cart.

Cheers!
