### ISSUE TITLE
Address suggestions are heavily Canadian :)

### ISSUE THREAD

**Issue by judbd** [snipcart/snipcart-v3-feedback#11]
All suggested address are Canadian at first, maybe narrow it with the client location (via IP) or the country of the shop set in the account preferences.

**Comment by couellet** [comment]
It's actually supported, but we (I actually 😬) used a fixed IP address for our tests before the beta and forgot to remove it 🤦‍♂

**Comment by couellet** [comment]
Hey @judbd just wanted to let you know that this was fixed a couple hours after we got your issue ;)

**Comment by judbd** [comment]
Thank you! **\*magasinage intensifies\***
