### ISSUE TITLE
Test payment impossible

### ISSUE THREAD

**Issue by judbd** [snipcart/snipcart-v3-feedback#12]
**Describe the bug**
In firefox, the payment div/form doesn't open, maybe due to a cross origin issue with payment.snipcart.com. Console displays a warning:

> Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://payment.snipcart.com/api/public/sessions. Raison : échec de la requête CORS.

Changed my CORS in htaccess (CSP also have to be changed to authorize https://payment.snipcart.com/ as `connect-src`) but no luck.

In Chrome the credit card form shows up but I can't test it, the stripe credit card doesn't work, maybe for the same reason. The Chrome console says

> Failed to load resource: the server responded with a status of 400 (Bad Request) for https://app.snipcart.com/api/cart/e3265dea-da17-48ad-9554-b18d99a7e3bc/pay

**To Reproduce**
1. Use html5 [boilerplate htaccess](https://github.com/h5bp/html5-boilerplate/blob/master/dist/.htaccess?ts=2#L11) just in case, not sure if it's the problem
2. Try to pay with the last firefox
3. Nothing happens
4. Do the same thing in the last Chrome, the Credit Card form appears, but throws an error 400 when tested with stripe CC test numbers.

**Expected behavior**
I would like to test the payment and have a validated payment with Stripe test number `4242 4242 4242 4242`

**Screenshots**
In Chrome:
![image](https://user-images.githubusercontent.com/4228245/58129747-c5245f80-7c1a-11e9-8c4a-29a0e7d41cc9.png)

**Comment by thatfrankdev** [comment]
Thank for reporting this!

Is it possible the page you're testing Snipcart on is loaded directly from your file system using the `file://` scheme?

Note that changes to `.htaccess` files will have no effect when viewing pages that way.

**Comment by judbd** [comment]
I use kirby CMS V3 as website tool, served by XAMPP via localhost so I don't think I use the `file://` way. Tell me what can I check to help you further.

**Comment by thatfrankdev** [comment]
@judbd It would help us better isolate the issue if you could send a screenshot of your browser developer tools' Network tab.

Thanks!

**Comment by judbd** [comment]
Yes no problem, here it is (Chrome)

![image](https://user-images.githubusercontent.com/4228245/58183605-e4b99780-7caf-11e9-9d20-83e4ce4b23e7.png)

I think that I find the problem (at least for Chrome):

`{"reason":"CrawlingFailed","validationErrors":[{"expectedPrice":null,"expectedUnitPrice":null,"uniqueId":"00c5cc11-9031-4c46-a533-3f11dd683260","crawledUrl":"https://localhost/cyberspace-building-crew-shop/ecussons/from-tab-to-space","productId":"EMB-PATCH-DEVELOPERS-FROM-TAB-TO-SPACE","planId":null,"status":"Unreachable","minQuantity":0,"maxQuantity":0,"price":8.0,"possiblePrices":null,"productName":"From Tab To Space","message":null}],"message":"We have not been able to validate the order.","errors":{"amount":["error_crawling_failed"]}}`

The crawler can't find the page at localhost (so it's 100% normal but maybe show an explicit error instead of `error.undefined`)

**For Firefox I've no idea though, the CC form still doesn't show and network tab only shows 200 OK status.**

(Firefox)

![image](https://user-images.githubusercontent.com/4228245/58184013-9b1d7c80-7cb0-11e9-8a8b-37e8a22f8f3d.png)

**Comment by thatfrankdev** [comment]
Thanks @judbd,

The Chrome issue has been documented and planned; it has to do with displaying clear error messages in some areas of the cart.

Now, in the second screenshot you sent, I understand there is absolutely no request made to `payment.snipcart.com` to load the payment form? When you take a look at the DOM of your page, is there an `iframe` element in the Payment step markup? Are there errors in the console?

I couldn't manage to reproduce the issue when testing with Firefox, so if we could see this problematic setup live somewhere, it could help us see what's wrong. Let me know if that's possible for you.

Thanks

**Comment by judbd** [comment]
Hello, Just identified the problem yesterday on another website: it was my privacy badger addon going rogue and blocking URLs after some repeated tests (so not consistent behavior and I could not track it). Took me 2 days to solve on my other project 😅.

So no worries, except for the unclear Chrome error, everything is fine on Firefox. I'm really sorry as it was a rookie mistake but the request was not bloqued at first, then the the console error was misleading at least (no "blocked_by_client, just the mysterious CORS error)

Really sorry about that.

**Comment by thatfrankdev** [comment]
@judbd Thanks for getting back to me.

No worries, really. In fact, as a purely JAMstack tool, we are well aware that privacy add-ons can sometimes harm our product's stability, so that's good to be knowledgeable of the problematic ones.

Cheers, and thanks for all this feedback you give us 😄
