### ISSUE TITLE
Tab-driven checkout

### ISSUE THREAD

**Issue by gabrielrobert** [snipcart/snipcart-v3-feedback#14]
Actually, it is not possible to complete checkout process using the tab key to jump from one field to another. I think it would be great for accessibility and power users.

1) Being able to click "Checkout ->" using keyboard
2) Being able to jump from "Apt/Suite" to "I don't see my address"
3) etc...

**Comment by thatfrankdev** [comment]
Thanks for reporting this @gabrielrobert. We'll definitely work on making all actionable elements accessible via keyboard.

**Comment by couellet** [comment]
Thanks for the feedback @gabrielrobert, this has been improved in the last release, we still have to deal with the "Enter" keypress on the credit card form, but this is already listed in our backlog, so I'll close this issue.
