### ISSUE TITLE
"Address" textbox height versus "Apt/suite" textbox height

### ISSUE THREAD

**Issue by gabrielrobert** [snipcart/snipcart-v3-feedback#15]
A picture is worth a thousand words.

![image](https://user-images.githubusercontent.com/5783827/58171415-f5442080-7c63-11e9-825f-16ef4d3ece90.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0.3729.157

**Comment by thatfrankdev** [comment]
Thanks @gabrielrobert ! 🚀

**Comment by couellet** [comment]
Fixed in a recent release.
