### ISSUE TITLE
"Processing payment..." is not vertically aligned

### ISSUE THREAD

**Issue by gabrielrobert** [snipcart/snipcart-v3-feedback#16]
A picture is worth a thousand words.

![image](https://user-images.githubusercontent.com/5783827/58172637-18bc9a80-7c67-11e9-9f5b-674299d4e8d7.png)

 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0.3729.157

**Comment by thatfrankdev** [comment]
Thanks! 😃

**Comment by couellet** [comment]
Fixed now with the changes we made to our CSS rules. We'll be dropping more improvements on that end in the next beta release.
