### ISSUE TITLE
Missing billing icon in order confirmation screen

### ISSUE THREAD

**Issue by gabrielrobert** [snipcart/snipcart-v3-feedback#17]
The missing icon should be at the end of the checkout process. A picture is worth a thousand words.

![image](https://user-images.githubusercontent.com/5783827/58172980-11e25780-7c68-11e9-9e42-619a792bfac8.png)

- OS: Windows 10
- Browser: Chrome
- Version: 74.0.3729.157

**Comment by thatfrankdev** [comment]
Definitely 🥇

**Comment by couellet** [comment]
Fixed in the most recent release.
