### ISSUE TITLE
Add address complement field

### ISSUE THREAD

**Issue by judbd** [snipcart/snipcart-v3-feedback#18]
It's not rare in France to have a detailed address on top of the regular one (number + street) and the apt number. It also can be the name of the company, or the person inside a company.

It's very important for the shipping, so it will be a nice addition to the address field.

**Comment by couellet** [comment]
Hey there,

We should add a feature in the next release that will allow you to add custom fields directly into the overridable templates. So you'll be able to collect more information if required such as a detailed address.

**Comment by skeary** [comment]
Having more flexibility would be good but having an optional company field would seem to help in a lot of cases. Currently, if you have an address of the form below (which I don't think is that unusual) it's a bit confusing to know what to enter where:

Ada Lovelace
IBM
Level 10
15 Some Street
Some City
....

You can certainly make it work with the current input but it seems harder than it should be. BTW the address searching feature is very nice, though :)

**Comment by mdings** [comment]
I'd like to add to this that it would also be good to be able to alter labels and remove unwanted fields altogether. The province/state field isn't used in The Netherlands for example. Being able to hide it in this case would be good towards a better user experience in my opinion.

**Comment by thatfrankdev** [comment]
Hi there,

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
