### ISSUE TITLE
Multiple versions of vue-class-component

### ISSUE THREAD

**Issue by gabrielrobert** [snipcart/snipcart-v3-feedback#2]
It looks like `vue-class-component` is imported twice using different versions.

![image](https://user-images.githubusercontent.com/5783827/58111232-17379780-7bbf-11e9-8285-6b16e8cc1380.png)

**Comment by JeanSebTr** [comment]
I'll close this one as it's very specific and we'll address that when working on the packaging of the theme. We'll follow up in #1 for general bundle size improvements :)
