### ISSUE TITLE
How to Add 'Total Cart Items' on Site?

### ISSUE THREAD

**Issue by mtclmn** [snipcart/snipcart-v3-feedback#20]
In v2, you could add the Total Items / Total price in, say, the header of the site.
```
<div class="snipcart-summary">
    Number of items: <span class="snipcart-total-items"></span>
    Total price: <span class="snipcart-total-price"></span>
</div>
```
It doesn't appear to be working the same with v3. Is there, or will there be an updated snippet for that?

**Comment by thatfrankdev** [comment]
Thanks Matt,

This will still be supported, but we haven't yet decided on how to integrate these placeholder tags into our new architecture.

**Comment by couellet** [comment]
Hey Matt,

This has been done in the last release, you'll find the documentation right [here](https://snipcart-docs-v3.netlify.com/cart/v3/the-cart).

**Comment by tpiros** [comment]
@couellet the link shows a 404.

**Comment by couellet** [comment]
@tpiros we released our new docs since then, here's the updated URL: https://docs.snipcart.com/v3/setup/cart-summary
