### ISSUE TITLE
Multiple Stores per User

### ISSUE THREAD

**Issue by mtclmn** [snipcart/snipcart-v3-feedback#21]
I'm unsure if this is something possible for v3 of Snipcart (and perhaps this is not the correct place to mention) - but it would be really nice if I could have multiple Snipcart stores tied to a single email.

**Describe the solution you'd like**
I'd like to be able to sign in to my Snipcart account and jump between multiple stores easily. Currently, it seems I have to have a unique email for each store. 
As a developer working on potentially many stores at once, it would be really handy to jump between them from within Snipcart, once logged in.

**Additional context**
I think Shopify does a nice job of this - especially handing "In Development Stores" and "Live/Managed Stores".

**Comment by couellet** [comment]
Hey Matt,

Thanks for the feedback here. After the launch of the final version of the v3, we should start working on a developer portal that should fix this issue.

I don't think this is in the scope of the v3 itself, so I'm gonna close this issue, but, if you're subscribed to our newsletter, we'll let people know when we start working on this!
