### ISSUE TITLE
Documentation sidebar menu not working on Firefox

### ISSUE THREAD

**Issue by michaelroper** [snipcart/snipcart-v3-feedback#22]
**Integration URL**
https://snipcart-docs-v3.netlify.com/

**Describe the bug**
On the v3 documentation site, the sidebar menu does not function in Firefox (it works in Chrome). In the Dev console, there is the following error: `SyntaxError: invalid regexp group`, but that is it.

**To Reproduce**
1. Go to https://snipcart-docs-v3.netlify.com/ in Firefox
2. Click on hamburger menu...
3. Nothing happens...

**Expected behavior**
Menu should be displayed by default, and toggle when hamburger menu is clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/60287/59157370-2f267b00-8adc-11e9-8b33-0f9fc15e02b8.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox Nightly
 - Version 69.0a1

**Comment by JeanSebTr** [comment]
Fixed thanks! 😃
