### ISSUE TITLE
Can't have 0 as item-price

### ISSUE THREAD

**Issue by erikgeelhuijzen** [snipcart/snipcart-v3-feedback#23]
have a  data-item-price="0.00"or  data-item-price="0" leads to the follwing error:

snipcart.js:23 Uncaught Error: Required data attribute "item-price" value is incorrect
    at e.priceValueSelector (snipcart.js:23)
    at e.getRequiredAttributeValue (snipcart.js:23)
    at new e (snipcart.js:23)
    at Object.snipcart-add-item (snipcart.js:23)
    at a.onDocumentClick (snipcart.js:23)

 data-item-price="0.00000000001" does work.

**Comment by couellet** [comment]
Thanks for the feedback! We'll keep you posted.

**Comment by JeanSebTr** [comment]
Hey @erikgeelhuijzen !

This will be fixed in 3.0.1 – releasing it in a few hours :)

**Comment by erikgeelhuijzen** [comment]
Hi there,

Unfortunately still not working for me:
[image: image.png]
Using the following button:
[image: image.png]
Also tried price defined as "0.00" Not working as well.

What am I doing wrong? Hope to hear from you soon,

thanks, Erik

**Comment by couellet** [comment]
Erik,

Can't see the images here, did you update to the latest Snipcart version? If so, can we see a live example somewhere?

**Comment by erikgeelhuijzen** [comment]
Wow, my bad. So sorry, didn't update. Tried it after updating and working
fine now.

Thanks for your quick response, sorry to have bothered you with this
question,

Erik
