### ISSUE TITLE
Passing through custom value not working anymore

### ISSUE THREAD

**Issue by erikgeelhuijzen** [snipcart/snipcart-v3-feedback#24]
See attached image...
The code to passthrough custom values works in V2, in V3 not anymore?

![custom_value](https://user-images.githubusercontent.com/52071964/60015161-11801680-9683-11e9-9e46-43dc3d25f34c.png)

Code using suggested syntax in documentation V2. Something like this:
<script type="text/javascript">
jQuery('#sterkte-rechts').change(function() {
    jQuery('#order-button').data('item-custom1-value', jQuery(this).val());
});

jQuery('#sterkte-links').change(function() {
    jQuery('#order-button').data('item-custom2-value', jQuery(this).val());
});

**Comment by thatfrankdev** [comment]
This way if changing the properties of your products is no longer supported since we do not rely on jQuery anymore. Updating values in the jQuery data object is now invisible to Snipcart.

What you'll want to do here is change the HTML attributes of the element itself. With jQuery it can be done using the `attr` function

**Comment by erikgeelhuijzen** [comment]
Thank you Francis for the reply. I'm not sure though how I can implement
this. Can you give me a small example? Thanks in advance.

**Comment by thatfrankdev** [comment]
@erikgeelhuijzen This can be as little a change as updating this: `jQuery('#order-button').data('item-custom1-value', jQuery(this).val());`

to this: `jQuery('#order-button').attr('data-item-custom1-value', jQuery(this).val());`

**Comment by erikgeelhuijzen** [comment]
Thanks @thatfrankdev for your quick reply. Unfortunately it does not work at my end using your example. The listner works as it stops at the breakpoint, the value of the custom attribute is also passed in correctly with jQuery(this).val() but somehow it still does not work. Any suggestions?

![custom_value_2](https://user-images.githubusercontent.com/52071964/60108943-c1c84a80-9769-11e9-8c15-4338282fec3a.png)
