### ISSUE TITLE
React or Vue Official Library

### ISSUE THREAD

**Issue by gabalicious** [snipcart/snipcart-v3-feedback#25]
**Is your feature request related to a problem? Please describe.**

> With this new Snipcart version, we aim to achieve three goals... 2) Let developers work with the stack of their choice, without compromise...

So snip-cart is cool but as I'm playing with version 2 I'm seeing that it heavily relies on dom the api.  This makes it harder to integrate with my React app and is causing some bugs with the cart.  I might use a third party library but I'd rather have some official libraries that you guys maintain for popular frameworks like React, Vue, or Angular.  Letting developers use the stack of their choice like you mention as your mission to me means allowing developers to easily integrate with the platform of their choice.  

**Describe the solution you'd like**
I would love an official React or Vue library.  The solution currently  use jquery and you should easily be able to use yarn/npm to add it to your existing project.  

**Describe alternatives you've considered**
As mentioned above there's a third party React library that I will try but it's maintained by one individual.  I might contribute to it if it's currently broken since it hasn't been updated in 2 years.  

**Additional context**
[Edit]: I see version 3 is a bit different.  But please allow me to use npm package so I can require/import it in my code.  I might try the beta possibly use it in production if it works better than 2 on my react app.

**Comment by JeanSebTr** [comment]
Hi @gabalicious ! 😄 

This is all planned. Not a specific Vue or React library, but a standalone SDK that specifically built to be used with those modern frameworks – and available through npm.

You can have a bit more details on [how it will be done in that post](https://snipcart.com/blog/redux-vue). Short story: our SDK manages all Snipcart logic + the cart state and expose it through a Redux Store.

For now, we're working on stabilizing all API before releasing anything on npm. Once we do, we want to make sure developers can use any version of the package without the risk that we break compatibility at some point.

The beta of our Cart V3 is built on top of that SDK.

**Comment by gabalicious** [comment]
@JeanSebTr That's great news!

**Comment by thatfrankdev** [comment]
We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
