### ISSUE TITLE
Localhost testing failing due to security checks

### ISSUE THREAD

**Issue by kilgoretrout** [snipcart/snipcart-v3-feedback#27]
Not sure if there is a way round this via config, but here is the issue....

**Describe the bug**
Security checks do not allow me to complete checkout when running the site from localhost:4200 in test mode.

**To Reproduce**
1. Set environment mode to test
2. Follow check out process until end i.e. entering credit card details.
4. See error errors.undefined
5. Developer logs show: The item at URL 'http://localhost:4200/test' is not on an allowed domain.

**Expected behavior**
Checkout completes no error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/1177596/65701120-ad516200-e078-11e9-9260-b92f92cbd4bf.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome
 - Version 77.0.3865.90

**Comment by JeanSebTr** [comment]
Hi @kilgoretrout !

You can [use ngrok to test on localhost](https://snipcart.com/blog/develop-a-snipcart-powered-website-locally-using-ngrok) :)

**Comment by kilgoretrout** [comment]
Thanks for the info 👍
