### ISSUE TITLE
Cannot use currency different from USD, also not multiple currencies

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [snipcart/snipcart-v3-feedback#29]
Even though the currencies are correctly set in the Snipcart dashboard, the cart on the client side always displays USD. Also [setting multiple currencies](https://docs.snipcart.com/configuration/multi-currency) isn’t working.

**Comment by couellet** [comment]
Hey there,

Thanks for the feedback! Multiple currency is a feature that we'll bring back in the next couple of releases. We'll update our docs soon with the missing features we're planning on brining back.

**Comment by dsdsdsdsdsds** [comment]
OK, thanks. What about using a default currency other than USD? Will that be available anytime soon?

**Comment by couellet** [comment]
The cart will use your first configured currency by default, if it's set to Euros for instance, this is what we're going to use.

However, with the new release, we started using the browser API to display currency instead of the settings we had to set in the dashboard before.

**Comment by messismore** [comment]
> However, with the new release, we started using the browser API to display currency instead of the settings we had to set in the dashboard before

What does that mean? Where do I set the currency?

**Comment by JeanSebTr** [comment]
@messismore currencies are [configurable in the dashboard](https://app.snipcart.com/dashboard/settings/regional). However, the V3:

- use built-in browser formatting instead of the custom number format
- only supports your default configured currency (**for the moment**)
- doesn't allow to switch currency from the JS AP (**for the moment**)

We'll fix the last two points ASAP

**Comment by JeanSebTr** [comment]
Make sure to use `V3.0.1` and clearing any previous Snipcart cookie

**Comment by olivM** [comment]
any update on multicurrency support in v3 ?

**Comment by JeanSebTr** [comment]
It's been planned in a few releases. Can't promise a specific ETA yet.

**Comment by goldcoders** [comment]
yes any update? im having hard time implementing this :(
but i dont wanna use snipcart v2

**Comment by pgmichael** [comment]
Just a heads up that multi-currency was added in `v3.0.11`. More details on how to achieve this in [our documentation](https://docs.snipcart.com/v3/setup/multi-currency).

Thank you for your patience!
