### ISSUE TITLE
Validation message: errors.incomplete_zip

### ISSUE THREAD

**Issue by gabrielrobert** [snipcart/snipcart-v3-feedback#3]
**Describe the bug**
Missing error message.

**To Reproduce**
1. Enter billing info
2. Enter shipping info
3. Use credit card #4242 4242 4242 4242
4. Use invalid postal code (for instance: "4")

**Expected behavior**
A clear and concise error message.

![image](https://user-images.githubusercontent.com/5783827/58111837-3be03f00-7bc0-11e9-80c9-905e93f57a7f.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - Browser: Chrome
 - Version: 74.0.3729.157

**Bonus point**
I live in Canada, my postal code is not integer-only. Is there a way to set "G1K3X0"?

**Comment by couellet** [comment]
Thanks for the report @gabrielrobert we'll flag this bug!

For the postal code, I think this has something to do with the credit card number, in this case, Stripe detects it's a US credit card number.

@thatfrankdev correct me if I'm wrong ;0

**Comment by gabrielrobert** [comment]
Same applies to incomplete number.

![image](https://user-images.githubusercontent.com/5783827/58172266-1148c180-7c66-11e9-808b-ad5ec9c16265.png)

**Comment by JeanSebTr** [comment]
This should be fixed [since we shipped localization in 3.0.5](https://docs.snipcart.com/v3/release-notes)!
