### ISSUE TITLE
Snipcart becomes non functional after 'Unable to update billing address snipcart.js:73:64470'

### ISSUE THREAD

**Issue by erikgeelhuijzen** [snipcart/snipcart-v3-feedback#30]
Snipcart becomes unresponsive after the following steps:
- put product in shopping-basket (press button)
- go to checkout
- try, without entering any address-data, to go to step 2
- see message required fields
- press 'continue shopping'
- pressing the product-button again results in nothing/no response

errormessage in console:
Unable to update billing address snipcart.js:73:64470

The only way to get it to work again is to delete site/browsing-history in browser-option-menu. Tried this in Chrome and Firefox, both same result.

**Comment by budparr** [comment]
may be a duplicate of https://github.com/snipcart/snipcart-v3-feedback/issues/6

**Comment by erikgeelhuijzen** [comment]
I do not get this error anymore after 3.0.1 update.
