### ISSUE TITLE
Listing payment options step on localhost returns a 422

### ISSUE THREAD

**Issue by bsmth** [snipcart/snipcart-v3-feedback#32]
**Integration URL**
localhost

**Describe the bug**
In the checkout process, after step 2 (shipping options) and clicking 'continue to payment' Step 3 (Payment) the Payments box fails to load any payment methods

**To Reproduce**
1. Go to 'Checkout'
2. When billing/shipping addresses filled out, select a shipping option
3. Click 'Continue to  Payment'
4. Payment options is empty

**Expected behavior**
A list of payment options is listed

**Screenshots**

![image](https://user-images.githubusercontent.com/43580235/67639731-9742f580-f8f3-11e9-9c7f-e0052e42217e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version n 77.0.3865.120 (Official Build) (64-bit)

**Additional context**
* Mollie is the payment gateway selected. 

The failing request is `PATCH` to 
https://payment.snipcart.com/api/public/sessions/{session-id} with 

```
{"paymentMethod":"card"}
```

and it returns a 422 Unprocessable Entity

**Comment by thatfrankdev** [comment]
Thanks for the detailed report @bsmth 

In its current state, Mollie support in the V3 is still facing some glitches here and there. Fixes are under active development at the moment and will be released pretty soon.

Cheers

**Comment by bsmth** [comment]
__Minor Update:__  following `3.0.4` - the payment options are now listed successfully, but I still get a `422` with the same PATCH request.

**Comment by thatfrankdev** [comment]
Hey @bsmth, I'll close this issue since the initial bug seems to be resolved. For further assistance on the HTTP 422 issue, please contact us via Intercom (support widget, bottom right of your merchant dashboard).

**Comment by bsmth** [comment]
**Solved:** I had a look at this problem again in the dev logs and found a `not on an allowed domain` error. By providing a prod URL (not localhost) with `data-item-url`, this 422 goes away in the browser. The misleading part was that I got this in the 422 response:

```json
message: "ForbiddenNot all required permissions (orders.write) for accessing this resource were granted."
```

Which led me down the path of checking API key permissions etc. The helpful doc was the following (helpfully linked in the developer logs) https://docs.snipcart.com/v3/security.
