### ISSUE TITLE
Checkboxes of payment step on mobile are distorted

### ISSUE THREAD

**Issue by geosaa** [snipcart/snipcart-v3-feedback#33]
On mobile, the checkbox of the payment steps looks weird (screenshot).
In addition, when only one shipping option is available, shouldn't that step be skipped? 

![image](https://user-images.githubusercontent.com/22175437/67676807-a3c25f00-f982-11e9-85ba-e37d8ad97304.png)

**Comment by couellet** [comment]
Fixed in the latest release!
