### ISSUE TITLE
URLs getting updated by Snipcart

### ISSUE THREAD

**Issue by skeary** [snipcart/snipcart-v3-feedback#34]
**Integration URL**

See https://github.com/skeary/snipcart-nextjs which is a fork of the snipcart-nextjs project, with the only changes made to switch to Snipcart v3, according to published instructions.

For specific changes made see last commit:
https://github.com/skeary/snipcart-nextjs/commit/5c218a99a2dbab1aaa6da74ea65d78eef8d6d902

**Describe the bug**

After installing the Snipcart v3 in a React Next.js app, the URLs displayed in the browser are being updated by Snipcart and I think this may have the potential to cause issues with client side routing etc. At the very least it's undesirable behaviour.

As an example, if you start the updated sample app and go to http://localhost:3000, you will see the address gets updated to http://localhost:3000/#/.

I've confirmed that it's the Snipcart.js code that is doing this by removing the reference to this file and seeing the problem going away. Putting the reference back in causes the error to occur again.

**To Reproduce**

Steps to reproduce the behaviour:
1. Clone the repo.
2. Install packages using `npm i`
3. Run `npm run dev`
4. Go to http://localhost:3000
5. Observe address changes to http://localhost:3000/#/

**Expected behavior**

I would expect the address to not be modified.

**Screenshots**

Incorrect address shown:
![image](https://user-images.githubusercontent.com/33426/67682766-0d665b80-f9cb-11e9-8244-737dc5eb8032.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04
 - Browser Chrome / Firefox
 - Version 77.0.3865.90 (Official Build) (64-bit) / 70.0 (64-bit)

**Additional context**

N/A

**Comment by JeanSebTr** [comment]
Thanks for the detailed report @skeary!

Using the hash to navigate in the cart is currently the less intrusive method to not interfere with the Navigation History API.

But of course, it shouldn't do anything unless the cart is in use. We'll test with a similar setup to not interfere with the main app's navigation.

**Comment by tilton** [comment]
Following this. Really hope to see it get resolved as i'm having the same problem.

**Comment by jgsimmerman** [comment]
I noticed the same thing with a Gatsby site and it would sometimes also append the hashtag before the backslash, like https://www.example.com/route123#/

**Comment by JeanSebTr** [comment]
At the moment it will do it systematically with any stack. However, it shouldn't affect your application's navigation as long as you use HTML5 mode (history API).

I understand the concern, but it shouldn't have a technical impact in normal circumstances (SEO or conflict with App's navigation). We've been told that it can conflict with [anchor links](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Linking_to_an_element_on_the_same_page).

If you find something that is conflicting, please provide a reproduction demo and a description of what is affected. This will help prioritize the issue 🙇

**Comment by hotdoy** [comment]
Shouldn't the url update only when the cart is deployed? It currently adds the # all the time.

**Comment by JeanSebTr** [comment]
@hotdoy that's the goal. That's something we'll fix in a future update.

**Comment by thatfrankdev** [comment]
Hi @

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

Several improvements have been made to the cart routing over the course of this year. Most problems people were facing regarding this are now fixed.

If you still need support or if you want to submit any kind of feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
