### ISSUE TITLE
Can get data-item-quantity to work. Only one item is added.

### ISSUE THREAD

**Issue by skeary** [snipcart/snipcart-v3-feedback#35]
**Integration URL**

See https://github.com/skeary/snipcart-nextjs which is a fork of the snipcart-nextjs project, with the only changes made:
* Switching to v3
* Adding a `data-item-quantity="3"` to the add to cart buttons

Note that this change to add a quantity greater than 1 is on the branch `test_quantity_add`:

https://github.com/skeary/snipcart-nextjs/tree/test_quantity_add

**Describe the bug**

Snipcart appears to be ignoring the `data-item-quantity` attribute. This attribute isn't documented in the main documentation, but it is referred to other (older) resources on the Snipcart site. Should this be supported with v3?

**To Reproduce**

Steps to reproduce the behaviour:

1. Clone the repo
2, Switch to `test_quantity_add` branch
3. Install packages using npm i
4. Run npm run dev
5. Go to http://localhost:3000
6. Add a product to the cart and observe that the quantity is set to 1 in the cart

**Expected behavior**

I would expect the `data-item-quantity` attribute to be honoured. It seems like a useful attribute to have :)

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04
 - Browser Chrome / Firefox
 - Version 77.0.3865.90 (Official Build) (64-bit) / 70.0 (64-bit)

**Additional context**

**Comment by thatfrankdev** [comment]
Thanks for reporting this @skeary. A fix for this is planned and should drop in on of the upcoming releases.

**Comment by JeanSebTr** [comment]
Hi @skeary !

`data-item-quantity` should be [fixed in 3.0.6](https://docs.snipcart.com/v3/release-notes)!
