### ISSUE TITLE
Use enter to confirm credit card information

### ISSUE THREAD

**Issue by jessecrouch** [snipcart/snipcart-v3-feedback#37]
Currently you must click on "Place order" to confirm an order. After entering CC info during checkout it would be nice to be able to hit "enter" rather than move the cursor and click.
![image](https://user-images.githubusercontent.com/202414/67815446-efedcc00-fa74-11e9-8c03-8c51884ca22e.png)

**Comment by couellet** [comment]
Thanks for reporting, this is definitely something we'll address in upcoming releases.

**Comment by thatfrankdev** [comment]
Hi @jessecrouch 

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
