### ISSUE TITLE
Incorrect ZIP code geocodings

### ISSUE THREAD

**Issue by jessecrouch** [snipcart/snipcart-v3-feedback#38]
On some addresses, particularly those I'm familiar with in Austin, TX - the geocoding of the zipcode is off. It shows one sort of near the areas, but is not a matching one for the address.

![image](https://user-images.githubusercontent.com/202414/67868553-26215f00-fafa-11e9-8908-8fc567a6f64c.png)
![image](https://user-images.githubusercontent.com/202414/67868566-29b4e600-fafa-11e9-95fd-951d54af9902.png)

73301 comes up repeatedly even though these should be 78704 and 78702, respectively. Seems to be off for other cities as well:
![image](https://user-images.githubusercontent.com/202414/67868680-48b37800-fafa-11e9-9f4d-f050508b87f0.png)

Should be 78681

**To Reproduce**
1. Go to the checkout stage in the cart
2. Type in a known address in the Billing Address section (https://www.google.com/search?q=2206%20santa%20rita%20austin%20tx)
3. Note the recommended zip vs the real zip
4. User has to hit "I don't see my address", delete the false address, and enter in their correct one

**Expected behavior**
The correct zip should show instead 

**Environment (please complete the following information):**
 - Tried in Chrome, Vivaldi, Brave, Safari on desktop
- Brave on mobile
- On my local test environment and deployed version (both in Test mode)

**Comment by jessecrouch** [comment]
Ok sounds good, thank you!

**Comment by thatfrankdev** [comment]
We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
