### ISSUE TITLE
Responsive Display Issue

### ISSUE THREAD

**Issue by marcodeluca** [snipcart/snipcart-v3-feedback#39]
Desktop, firefox browser - resized the window to test responsiveness. Seems like there is an issue with a div that either should be hidden or have the style adjusted. The # 1 in the background for step 1 Order Summary is clipped and, well the screenshot should explain it. Using a standard bootstrap site so... maybe a conflict with existing stylesheets, I'll test that out tomorrow and comment if I find something.

Otherwise looks and works great so far.

![Screen Shot 2019-10-29 at 4 01 52 PM](https://user-images.githubusercontent.com/968926/67898892-90a4c000-fb37-11e9-92a3-58bc4d05d8d6.png)

**Comment by marcodeluca** [comment]
I checked and did not see any conflicting CSS. I find this one aspect a little confusing to be honest - clicking the down caret on the price toggles between an order summary section and whatever step of the process you are on.

Assuming the intention is to overlap the order summary on top of the step, I think its just a margin issue:

```
.snipcart-cart-summary--small {
   ...
  */margin-top: 30px;*/
    margin-top: 15px;
}
```

The confusing part is its not intuitive to click on the caret to get an order summary, and because the theme is so minimal (which I like) the overlay which is part opaque and part transparent is a little confusing visually. It's not terrible, I see what you're going for and once you take a few seconds to click a few times it's understandable.

Just wondering if there's a better way to transition between the checkout process and the order summary.

**Comment by thatfrankdev** [comment]
Hi @marcodeluca 

So sorry we couldn't respond to this one sooner. I hope you were able to get support from us via your merchant dashboard or via email.

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
