### ISSUE TITLE
Documentation CDN URLs Broken

### ISSUE THREAD

**Issue by mtclmn** [snipcart/snipcart-v3-feedback#4]
It appears the CDN URLs in the docs return 404:
https://cdn.snipcart.com/themes/v3.0.0-beta.1/snipcart.js
https://cdn.snipcart.com/themes/v3.0.0-beta.1/snipcart.css

Adding `default` to the path seems to resolve to correct place:
https://cdn.snipcart.com/themes/v3.0.0-beta.1/default/snipcart.js
https://cdn.snipcart.com/themes/v3.0.0-beta.1/default/snipcart.css

**Comment by couellet** [comment]
Thanks for reporting! You're correct, the URL should contain `default`. We'll fix that ASAP.

**Comment by couellet** [comment]
Fixed!
