### ISSUE TITLE
Can't edit order summary at narrow screen sizes

### ISSUE THREAD

**Issue by messismore** [snipcart/snipcart-v3-feedback#40]
**Integration URL**
https://demo.snipcart.com/#/checkout

**Describe the bug** 
The order summary modal invoked by clicking the inverted chevron next to the shopping bag in the checkout flow is broken at narrow screen sizes.
Clicking anywhere (even the 'Edit' link) will dismiss the modal rather than editing the order.

**To Reproduce**
1. Place a item in the cart
2. Click 'Checkout'
3. Decrease the screen width until the page switches to single column layout
4. click the downward inverted chevron in the upper right
5. Click 'Edit'
6. The 'Order summary' modal disappears rather than showing the 'Edit order' modal.

**Expected behavior** 
A modal to edit the order should appear, as it does in the two column layout

 **Screenshots** 
![Snipcart Edit order](https://user-images.githubusercontent.com/5689189/67903737-af717980-fb6c-11e9-9378-9c7e8be7959c.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Safari, Firefox, Chrome

**Comment by thatfrankdev** [comment]
Thanks for reporting,

Well have a look at this issue and work on a fix.

**Comment by thatfrankdev** [comment]
Hi @messismore 

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
