### ISSUE TITLE
Slow loading times snipcart-components

### ISSUE THREAD

**Issue by erikgeelhuijzen** [snipcart/snipcart-v3-feedback#42]
I'm doing some speedtests in order to find things to optimize on my website running (for now) on netlify. Using Google's speedtest I can see that 2 components from snipcart take quite some time to load. Is there a way for me to improve this?

![image](https://user-images.githubusercontent.com/52071964/68777167-8b646c80-0631-11ea-9d80-6ac40cad6132.png)

**Comment by erikgeelhuijzen** [comment]
I have created a seperate component 'Snipcart.vue' and removed snipcart-entries from nuxt.config.js

Snipcart.vue:
<template>
    <div id="snipcart" data-api-key="MY_API_KEY" hidden></div>     
</template>

<script>
export default {
  head: {
    link: [
      { rel: 'stylesheet', href:'https://cdn.snipcart.com/themes/v3.0.2/default/snipcart.css' },
    ],
    script: [
      { src: 'https://cdn.snipcart.com/themes/v3.0.2/default/snipcart.js' }
    ],    
  },
}
</script>

In default.vue (in layouts) I lazyload the snipcart-component:
<template>
  <v-app light>
    <Header />    

    <div>
        <nuxt />
    </div>
    
    <Footer v-if="readyStateComplete"/>
    <Snipcart v-if="readyStateComplete"/>    
  </v-app>
</template>

<script>
const Header = () => import('@/components/Header')
// import Header from "@/components/Header"
const Footer = () => import('@/components/Footer')
// import Footer from "@/components/Footer"
const Snipcart = () => import('@/components/Snipcart')
// import Snipcart from "@/components/Snipcart"

export default {
  data: () => ({  
    readyStateComplete: false, 
    loading: false,
  }),       
  components: {
    Header,
    Footer,
    Snipcart,
  },
  mounted() {
    document.onreadystatechange = () => {
      if (document.readyState == "complete") {

        this.readyStateComplete = true

      }
    }
  },    
}
</script>

I'm not sure this is the way to go (I'm new at nuxt, vue, etc), but it seems to work. Snipcart is no burden on initial load this way boosting performance. Can you comment if this is a solid solution or should I use a different approach?

**Comment by JeanSebTr** [comment]
We generally recommend adding snipcart.js to [Nuxt's app template](https://nuxtjs.org/guide/views/#app-template) or [to nuxt.config.js](https://nuxtjs.org/guide/views/#default-meta-tags). This prevents common issues where multiple instances of `snipcart.js` are instantiated when navigating between pages.

You can, however, use your approach for the cart's CSS to force it to be loaded asynchronously – but you'll have to ensure it's not loaded multiple times if you want to preserve performances.

**Comment by thatfrankdev** [comment]
Hi @erikgeelhuijzen 

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com.

Thanks
