### ISSUE TITLE
Missing visual feedback when payment fail

### ISSUE THREAD

**Issue by erikgeelhuijzen** [snipcart/snipcart-v3-feedback#43]
When trying to make a test-payment I get either:
- Unable to process your payment
or
-
![image](https://user-images.githubusercontent.com/52071964/68942216-4e6eb600-07a8-11ea-8fae-eeb724a26b31.png)

**Comment by JeanSebTr** [comment]
Thanks for reporting this @erikgeelhuijzen !

The cart should at least indicate some details of the errors to not let the user waiting indefinitely. Could you open a conversation on the intercom widget from the dashboard so we can dive into the specifics of why this error happens for your account?

Thanks!

**Comment by erikgeelhuijzen** [comment]
After first attempt: HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
(Fetch)POST - https://app.snipcart.com/api/cart/a30d9b6a-691f-4233-af61-d55c49fe5e5d/pay

When pressing 'Continue Shopping' and trying to check out for a second time gives different errors: 0: Unable to get property 'SavePersonalAndPaymentData' of undefined or null reference
Autoformfill_ContentScript.js (1,20660)
HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
GET - https://payment.snipcart.com/form/Y2ExYzg1ZGYtZTY2Ny00MjgyLWE1ZDQtYjQ0MTQyNTVjYjcxNjM2Nzk0NTA4MDQ1NDQ4NjE4/xYzg4NjE-df1c2478-af7a-4e4e-8540-4d3e68f4b56d

Error initializing payment form: [object Object]

snipcart.js (23,307426)
[object Object]: {code: "payment_error_form_init", message: "Error loading payment form – try again later."}

**Comment by JeanSebTr** [comment]
I found the intercom issue. We'll follow up there as the underlying issue is probably related to an account config.

**Comment by JeanSebTr** [comment]
We've [improved the situation a lot in 3.0.6.](https://docs.snipcart.com/v3/release-notes). In future releases, we'll also be adding more feedback for developer integrating Snipcart about the specific issue they may have (crawling, configuration, ...).
