### ISSUE TITLE
payment icon are distorted

### ISSUE THREAD

**Issue by equilDev** [snipcart/snipcart-v3-feedback#44]
Snipcart 3.0.3 & 3.0.4 

**Describe the bug**
The payment icons are not displayed correctly at 3.0.3 and later (3.0.2 does work perfectly)

I used mollie at test mode on localhost

**Screenshots**
![image](https://user-images.githubusercontent.com/34444045/70223556-34434a80-174c-11ea-9292-faa5fdc08401.png)
![image](https://user-images.githubusercontent.com/34444045/70223591-47eeb100-174c-11ea-8484-8d91e2558e4a.png)
![image](https://user-images.githubusercontent.com/34444045/70223638-50df8280-174c-11ea-8e5b-c1a575e89c4b.png)

**Comment by equilDev** [comment]
I forgot to bind the 3.0.4 css ...

**Comment by JeanSebTr** [comment]
Gotcha! That made us discuss ways to prevent CSS errors and conflict, we'll keep that in mind if we can alleviate those kinds of errors.

**Comment by equilDev** [comment]
is it normal that some payment matheod like bank transfer have no icons ? (i'm using mollie as payment provider in test mode)
