### ISSUE TITLE
Add Separate Ship to:

### ISSUE THREAD

**Issue by budparr** [snipcart/snipcart-v3-feedback#47]
**Is your feature request related to a problem? Please describe.**
When checking out there is a provision for separate shipping address, but no "ship to:" so it assumes that the person/name shipped to is the same as that for billing.

**Describe the solution you'd like**
I'd like to have a "Ship to:" field in the shipping set of fields.

**Additional context**
![Screenshot 2019-12-23 11 09 22](https://user-images.githubusercontent.com/115347/71368007-af8e6400-2574-11ea-93ea-cb3254fa2839.jpg)

**Comment by Mapify-Team** [comment]
+ 1 for this. 

50% of our customers are buying as a gift to be directly shipped to another person. Currently they have to email us after ordering so we can change the name on the shipping address as the shipping address name assumes the same as billing address name.

If there is a solution to achieve this via customising the form fields please let us know. Christmas is coming and it is going to be a huge chaos if we have email contact with half our customers to make basic address changes.

**Comment by thatfrankdev** [comment]
Hi @budparr,

So sorry for the lack of feedback here. This has in fact been added quite recently, in 3.0.23.

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

Sometime in 2021, we will be rolling out a Discourse forum instance so we can have a decent community support channel.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks 🙇
