### ISSUE TITLE
Support for digital goods and data-item-file-guid attribute

### ISSUE THREAD

**Issue by 3reetop** [snipcart/snipcart-v3-feedback#48]
**Integration URL**
N/A

**Describe the bug**
Even if you pass a valid `data-item-file-guid` attribute, Snipcart 3 will ignore the attribute and will not send an email containing a download link.

**To Reproduce**
1. Upload a file through the Snipcart Dashboard and copy it's GUID.
2. Create a product on your site and set it's `data-item-file-guid` attribute to the GUID you copied earlier.
3. Make sure your shop is in test mode using a test API key, and attempt to make a purchase. (I used Stripe's test card information they offer to do the purchase)
4. When asked to enter an email, provide a real working email.
5. Complete the purchase.
6. Notice how upon submitting the payment, the confirmation screen and invoice are shown, and the invoice is successfully sent to the email you provided during checkout. However, no download link to the file is sent.

**Expected behavior**
That the email provided during checkout gets an email containing a link to the file.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 10 x64
 - Firefox Developer Edition 72.0b11

**Additional context**
I do not know what versions of Snipcart 3 this bug exists on, I've tested up to 3.0.2, and it does exist on that version as well as the latest 3.0.5, a temporary fix for this bug is to downgrade to Snipcart 2.

**Comment by YoavRheims** [comment]
Same bug appeared with Snipcart V2...

**Comment by JeanSebTr** [comment]
Hi @3reetop !

Digital Goods are [not yet available in the V3](https://docs.snipcart.com/v3/#important-notes).

I can't promise a precise ETA, but that feature should be available in a few releases.

**Comment by JeanSebTr** [comment]
Digital goods have been [released in 3.0.6](https://docs.snipcart.com/v3/release-notes)!
