### ISSUE TITLE
Utilize CSS Variables / Cascading Properties for ease of style customization

### ISSUE THREAD

**Issue by mtclmn** [snipcart/snipcart-v3-feedback#5]
I am liking the updated cart/checkout styling, however, I am wondering if things could be easier to customize through the use of css variables or through cascading styles.

To use fonts as an example...
If I wanted to use my site's brand font in Snipcart, it would be awesome if I could set:
`#snipcart {font-family: inherit}` and this would then use my site's body font.
Additionally, with the default Snipcart stylesheet, it looks like there are fonts explicitly set for many child elements, however these could also use `font-family:inherit` and pull from the `#snipcart` element. Especially elements that are setting the same font family as the root #snipcart element  – `.snipcart__cart__content__empty`, for example.

Currently it would require devs overwriting several places in order to change the font.

Perhaps even better, maybe these could be set through native CSS custom properties / variables, which could more easily be overridden by users?

Obviously, devs can use a custom stylesheet, but since there's a good base you've build, it would be nice to be able to update without throwing out the whole stylesheet.

**Comment by mtclmn** [comment]
Rough Idea for CSS custom props:
```
#snipcart {
    --font: 'Montserrat';
    --color-primary: blue;
    font-family: var(--font);
    color: var(--color-primary);
}
.snipcart__child__element {
    font-family: var(--font);
    color: var(--color-primary);
}
```
and then to override:
```
#snipcart.custom {
    --font: monospace;
    --color: pink;
}
```

**Comment by couellet** [comment]
Hey Matt,

Thanks for that, makes perfect sense. I like the idea of using CSS custom props. We'll surely consider that.

**Comment by couellet** [comment]
Hey Matt,

We made some improvements on that end, but we're currently working on some more fine tuning in our CSS styles.

You can find more details in the release notes [here](https://github.com/snipcart/snipcart-v3-feedback/releases/tag/v3.0.0-beta.2).
