### ISSUE TITLE
Add custom component to the cart

### ISSUE THREAD

**Issue by alexismoreau** [snipcart/snipcart-v3-feedback#50]
Hello,
I need to add a calendar to collect a date from the customer during checkout process.
Is it possible to do this with this version ?

**Comment by JeanSebTr** [comment]
Adding custom components to the cart is definitely something we're considering.

We actually talked about it yesterday in a brainstorming session. I can't promise it's something we'll tackle soon, but that may come later.

**Comment by thatfrankdev** [comment]
Hi @

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
