### ISSUE TITLE
Shipping section not updating correctly when applying discounts

### ISSUE THREAD

**Issue by ahsath** [snipcart/snipcart-v3-feedback#52]
**Integration URL**
https://bariatricreloads.com/

**Describe the bug**
Next to the shipping section in the order summary if you click on the edit button and add or removed products from the cart the shipping section is not updated correctly to reflect your discount, it is just when you click the edit button next to the shipping section then on the use this address button when it updates

**To Reproduce**
1. Go to integration URL
2. Add $1000+ worth of products to the cart
3. Fill in billing info and click on use this address button
4. Select either of the two options (Free shipping or Shipping)
5. In the order summary click on edit and remove products until it reaches a total below $1000
6. Close order summary

**Expected behavior**
The shipping section should update to reflect any discount when editing the contents of the cart directly in the order sumary

**Screenshots**
![ScreenRecording2020-01-25at51653](https://user-images.githubusercontent.com/37009121/73128256-7fcee380-3f9a-11ea-9c33-b3090138fee5.gif)

**Desktop (please complete the following information):**
OS: macOS X Catalina 10_15_0
Browser: Brave
Version: Chrome 79

**Additional context**
I'm using custom shipping and a discount, I don't know if this has anything to do with this, but users can skip paying shipping if editing the contents of the cart directly from the cart summary.

This was in 3.0.5 as well

**Comment by thatfrankdev** [comment]
Thanks for reporting @ahsath! We'll have this fixed in an upcoming release. 👍

**Comment by ahsath** [comment]
Hello there,

I'm not having this issue on `v3.0.11` and the bug I think it was fixed on `v3.0.10` per:

> Shipping rates are now updated automatically when cart content is changed from the order summary within the checkout screen.

But there is another problem. 

If you have items on your cart (more than $1000) leave and come back to continue the checkout process the discount is not being shown it's only when you add or remove items from the cart that it appear, it should show the discount right away.

**Comment by thatfrankdev** [comment]
Hi @ahsath 

So sorry we couldn't respond to this one sooner. I hope you were able to get support from us via your merchant dashboard or via email.

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you still need support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
