### ISSUE TITLE
Cannot test payments – 400 Bad Request Error

### ISSUE THREAD

**Issue by paulcosmos** [snipcart/snipcart-v3-feedback#54]
**Describe the bug**
Testing Snipcart payments results in an error:

Unable to process your payment
Please review your card details, or try again later. 

Checking the network tab in developer tools  shows a 400 Bad Request error. Tested with Firefox, Chrome and Vivaldi using the test card details provided in the checkout page, same issue across them all.

**Screenshots**
Screenshot from Firefox dev tools:

<img width="978" alt="Screenshot 2020-02-04 at 15 25 00" src="https://user-images.githubusercontent.com/24660807/73759261-9a0b7d00-4763-11ea-8489-4d0b754c31af.png">

**Comment by JeanSebTr** [comment]
Hi @paulcosmos !

Those are generally crawling or configuration errors. You can open a conversation on the support (chat widget in the lower right corner of the dashboard) and we'll be able to help you more specifically with this.

**Comment by roowilliams** [comment]
@paulcosmos did you get this resolved? Currently experiencing the same and up against the wall with timeline 😨
