### ISSUE TITLE
Checkout not validating altered custom options

### ISSUE THREAD

**Issue by claudiucelfilip** [snipcart/snipcart-v3-feedback#56]
**Integration URL**
https://demo.snipcart.com/#/
This also affects my local project.

**Describe the bug**
The selected custom option doesn't seem to be validated on Place Order.

**To Reproduce**
1. Go to https://demo.snipcart.com/#/
2. Open DevTools and edit the "data-item-custom1-options" attribute for "Buy 1 Physical Copy ($79.95)" button and change it from "Black|Brown|Gold[+300.00]" to "Black|Brown|Gold" (see "Button edit" screenshot)
3. Click the "Buy 1 Physical Copy ($79.95)"
4. In the Cart Summary, select Gold Frame Color.
5. Click Checkout 
6. Go through all checkout steps (I filled in dummy values and used 4242 42... credit card)
7. Click Place Order
8. The purchase goes through and Starry Night with Golden Frame at no extra cost. (see. "Successful purchase" screenshot)

**Expected behavior**
Clicking Place Order should have triggered a "Some items in your cart are invalid" error.

**Screenshots**
Button edit
![image](https://user-images.githubusercontent.com/2749938/74531116-751dc380-4f34-11ea-8910-593a0890692c.png)

Successful purchase
![image](https://user-images.githubusercontent.com/2749938/74531160-8961c080-4f34-11ea-9f44-1ffa773178d8.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 79

**Comment by thatfrankdev** [comment]
Thanks for reporting this @claudiucelfilip. We'll have a look at the issue and plan a fix if needed.

**Comment by thatfrankdev** [comment]
Hi @claudiucelfilip 

This issue has been fixed and custom fields modifiers are now all validated correctly.

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com.

Thanks
