### ISSUE TITLE
Validation error when adding multiple products through SDK

### ISSUE THREAD

**Issue by peterurban** [snipcart/snipcart-v3-feedback#57]
**Describe the bug**
When passing an array of product definition objects to Snipcart.api.cart.items.add I get a validation error (400). When passing a single object it works as expected. I am using the newest (3.0.8) version of the SDK.

```
try {
        await window.Snipcart.api.cart.items.add([
          {
            id: this.selectedItems[0].id,
            name: this.selectedItems[0].name,
            price: 0,
            fileGuid: this.selectedItems[0].file,
            url: '/validation',
            quantity: 1
          },
          {
            id: this.selectedItems[1].id,
            name: this.selectedItems[1].name,
            price: 0,
            fileGuid: this.selectedItems[1].file,
            url: '/validation',
            quantity: 1
          }
        ])
      } catch (error) {
        console.log(error)
      }
```

**Expected behavior**
Should add each product to the cart.

**Additional context**
All my products point to the same validation url; a static page containing all products.

**Comment by JeanSebTr** [comment]
Hi @peterurban !

We seem to have a typing error in our documentation.

The `Snipcart.api.cart.items.add` signature should be: `add(...items: Item[])` meaning that this method receive a variable number of products as arguments and not an array as first argument.
