### ISSUE TITLE
Stripe payment gateway Bug

### ISSUE THREAD

**Issue by jbty** [snipcart/snipcart-v3-feedback#58]
I report the bug for snip V2 here because the isn't repo for v2 feedback.

I use snipcart v2 whith stripe payement gateway for subscriptions working.

In test environment, when I purchase product n my store, when I have to enter the pay card , I got there errors in console:
[Image of console errors](https://i.ibb.co/Ctvgth2/Annotation-2020-02-26-192616.png)

I do not know what to do

**Comment by JeanSebTr** [comment]
Hi @jbty !

Could you contact us on support?
email `geeks@snipcart.com` OR use the chat widget in the dashboard.
