### ISSUE TITLE
Initiate Checkout and Payment details event

### ISSUE THREAD

**Issue by Joeldorne** [snipcart/snipcart-v3-feedback#59]
Is there an Event for  Initiate Checkout and Adding Payment Details?

The following are needed for the Facebook Pixel.

- Initiate Checkout
The start of a checkout process. 

- Add Payment Info
The addition of customer payment information during a checkout process.

https://docs.snipcart.com/v3/sdk/events

**Comment by thatfrankdev** [comment]
Hi @Joeldorne 

So sorry we couldn't respond to this one sooner. I hope you were able to get support from us via your merchant dashboard or via email.

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you still need support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
