### ISSUE TITLE
Checkout Step 1 has Billing Address validation Error on Localhost

### ISSUE THREAD

**Issue by mtclmn** [snipcart/snipcart-v3-feedback#6]
**Integration URL**
localhost

**Describe the bug**
When clicking through the Checkout, from Step 1 (Billing) to Step 2 (Shipping), I am unable to move past the 1st step.
Console error gives: `Unable to update billing address - code: "snipcart_error_validation_failed"`.
I chose an address from the autocomplete dropdown, and it still gave this error.

**To Reproduce**
1. Go to 'Checkout'
2. Enter Address, or Select from Address Autocomplete
3. Click 'Continue to Shipping'
4. See loading spinner, but does not proceed to step 2. Error logged to console.

**Screenshots**
![image](https://user-images.githubusercontent.com/4490155/58126854-fc2a4f00-7be1-11e9-9487-927afc5eaea7.png)

**Comment by couellet** [comment]
Would you mind sharing with us the query string you use in the address autocomplete? You can send it to charles@snipcart.com if you'd prefer!

**Comment by mtclmn** [comment]
@couellet 
In this case, I clicked "I don't see my address" and entered "123 Main St, Toronto, ON, CA, M4B 1B3".

I did notice when I refresh the page, it jumps me to step 2 with the address saved, but I click "Edit" on step 1, then click "Continue to Shipping", I get the 400 error again.

**Comment by brandnewguys** [comment]
Same error but this time hosted on Netlify.

**Comment by erikgeelhuijzen** [comment]
Same sort of error, can't get to payment-step due to this error:
![shipping_error](https://user-images.githubusercontent.com/52071964/59919881-f4500b80-9428-11e9-83db-154112c3bb41.png)

**Comment by thatfrankdev** [comment]
@erikgeelhuijzen Have you clicked on an address suggestion in the auto-complete list, or did you clicked "I don't see my address" and used the full form?

Thanks

**Comment by couellet** [comment]
Also @erikgeelhuijzen have you the shipping enabled for your account? The current beta requires you to enable at least one shipping method, we will be add support for accounts without shipping in one of the next beta releases.

**Comment by erikgeelhuijzen** [comment]
Shipping is enabled. I have defined custom shipping rules for the
Netherlands. I tried today after I checked and got a different error
message.
[image: image.png]

**Comment by erikgeelhuijzen** [comment]
> @erikgeelhuijzen Have you clicked on an address suggestion in the auto-complete list, or did you clicked "I don't see my address" and used the full form?
> 
> Thanks

I did use the 'I don't see my address' option and completed the full form.

**Comment by jericho1ne** [comment]
I have the same issue on localhost

**Comment by brandnewguys** [comment]
How are things coming along? Is there a timeline? We need to decide whether we’re going with v2 for now or hold out for v3 for a project launching in september.

**Comment by JeanSebTr** [comment]
Hi all,

I just realized we closed that issue without providing much context.

The issue was caused by the address autocomplete which was returning incomplete address details. Thus the address failing validation.

For now, we've removed the address autocomplete until we implement a better address autocomplete source.
