### ISSUE TITLE
Checkout fails to update billing address

### ISSUE THREAD

**Issue by trevoreyre** [snipcart/snipcart-v3-feedback#61]
**Integration URL**
https://dev.touchephotography.com

**Describe the bug**
Checkout keeps failing after entering the billing address.

**To Reproduce**
1. Go to https://dev.touchephotography.com
2. Select any photo, select material/size and add to cart
3. Go to checkout
4. Enter billing information and click "Continue to shipping"
4. View 500 error in developer console

**Expected behavior**
Billing address updates and allows to continue checkout process

**Screenshots**

![Screen Shot 2020-04-22 at 12 02 02 AM](https://user-images.githubusercontent.com/6662070/79946091-826f9680-842c-11ea-98e8-97b2b9671d60.png)

![Screen Shot 2020-04-22 at 12 02 48 AM](https://user-images.githubusercontent.com/6662070/79946144-9e733800-842c-11ea-9613-b924f1c3d5ed.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina v10.15.4
 - Browser: Chrome
 - Version: 81.0.4044.122

**Additional context**
I was using Snipcart v3.0.5 and seeing the error `Unable to update billing address` at this same step when trying to enter billing information at checkout, similar to #6. I updated to v3.0.11 to try to fix that error, and now I'm seeing the error in this issue. It's happening at the same point in the checkout flow, but now it's a generic system error, `A 'system' error occured in Snipcart.undefined`.

**Comment by thatfrankdev** [comment]
Thanks for reporting this @trevoreyre. We'll investigate and get back to you in the support thread you opened 👍

**Comment by trevoreyre** [comment]
I did end up getting this sorted out. I had the TaxCloud integration turned on, but it wasn't fully configured on the TaxCloud side. I turned off the integration and everything is working fine again. It would be nice if there was a more descriptive error message in that case, though.
