### ISSUE TITLE
Checkout and payment processing through totally custom UI (raw API calls)

### ISSUE THREAD

**Issue by luzzif** [snipcart/snipcart-v3-feedback#62]
Is it possible to implement the payment flow without using your premade UI? I'd like to integrate Snipcart in my React app through raw API calls. I made it work when adding/removing/editing items in cart, but I'm finding difficulties implementing the actual checkout logic (the official SDK reference is not clear at all).

**Comment by JeanSebTr** [comment]
Hi @luzzif !

That's the goal of the architecture we used for the v3. The cart UI is built on top of a separate SDK/API. However, at the moment, it is considered unsupported to not use the provided UI.

That's something we'll allow eventually by packaging our SDK without the UI.
