### ISSUE TITLE
Can't find any shipping rates for my country

### ISSUE THREAD

**Issue by AdrianFahrbach** [snipcart/snipcart-v3-feedback#63]
**Integration URL**
I set all shipping options to worldwide as a workaround, but I can reproduce this issue in our staging environment and give you access if necessary.

**Describe the bug**
The Snipcart API returns an error that says that it can't find any shipping rates when I restrict the shipping of my custom shipping methods to Germany even though I am in Germany.

**To Reproduce**
1. Make sure that you're location is Germany.
2. Go into the Snipcart dashboard and enable custom shipping methods
3. Restrict the location of all shipping methods to Germany
4. Open the cart and you should see the error message

**Expected behavior**
It should find my custom shipping methods.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 81.0.4044.129

**Additional context**
I just upgraded from V2 and the shipping worked fine there.
My document is set to this:
`<html lang="de">`

**Comment by JeanSebTr** [comment]
Hi @AdrianFahrbach 

This is usually a configuration issue with the account and not something related to the cart V3.

Could you contact us on support? geeks@snipcart.com
