### ISSUE TITLE
More template documentation required

### ISSUE THREAD

**Issue by benwakeford** [snipcart/snipcart-v3-feedback#64]
I've added a custom checkbox to the billing section, but I need it to be required to be checked (i.e. over 18). There's nowhere that shows me how to achieve this. In looking at the templates, I see that the originals use a <snipcart-error-message> tag, but this is not working for custom fields:

```
<div class="snipcart-form__field-checkbox">
  <snipcart-checkbox name="over18"></snipcart-checkbox>
  <snipcart-label class="snipcart__font--tiny snipcart-form__label--checkbox" for="over18">
     I confirm that I am at least 18 years old.
  </snipcart-label>
  <snipcart-error-message name="over18">Please confirm you are over 18</snipcart-error-message>
</div>
```

In addition, I need to display some fields conditionally on whether another checkbox is ticked. Again, there are no pointers on how to achieve this in the documentation. There's mention of a v-if command, but I'm unable to get this working.

So:

(a) are you able to clarify the two points above for me here (if so, much appreciated), and
(b) can you provide more documentation for people who are unable to invest time in learning Vue.js how to achieve additional basic functionality like this? Even if it's just a linked blog article.

Thanks in advance!

**Comment by andreavettore** [comment]
Same! as @benwakeford wrote, I need to display some fields conditionally on whether a checkbox is checked. I can't find this in the doc.

Thank you

**Comment by benwakeford** [comment]
Hey @andreavettore 

I ended up getting in touch with their support directly and they created a Pen for me which shows you how to do this. Hopefully they won't mind me posting it here to help you out.

[https://codepen.io/couellet/pen/vYNQJeG?editors=1010](https://codepen.io/couellet/pen/vYNQJeG?editors=1010)

> In the codepen above, I show you an example on how to display a custom field conditionally to another one. I also added the required attribute on the second checkbox that is shown when checking the first custom field. The example also overrides the cart template, so your other question about disabling checkout if subtotal if the cart is lower than 40$ is also possible.

In the demo, you need to increase the number of items to 3 to get from the cart to the checkout, then you'll see a Subscribe to Newsletter checkbox, which shows another field when ticked.

Obviously the code is all there for you, but the critical bit is adding this piece of logic to the initially hidden checkbox:

`<fieldset class="snipcart-form__set" v-if="state.customFields.find(x => x.name === 'subscribeToNewsletter' && x.value)">`

Hope that helps!

**Comment by filippolcr** [comment]
Some Vue Warn for me because I'm using pen's code in a vue template
Have you implemented with success?

It's possible to use this in a Vue component?
I didn't find any example in the docs.

> Unknown custom element: <billing> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

> Unknown custom element: <snipcart-checkbox> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

> Unknown custom element: <snipcart-label> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by benwakeford** [comment]
Hi @filippolcr - I personally only implemented some portions of it at present, but the whole pen does work. The code won't be a copy/paste situation; you'll need to tailor it carefully to your specific use case.

I would recommend contacting the Snipcart support; they were very helpful when I contacted them directly about coding queries.

**Comment by thatfrankdev** [comment]
Hi there,

So sorry we couldn't respond to this one sooner 🤦

As you may have figured out, this clearly was not considered as an official support channel for us. In fact, we are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

Thanks *a lot* to @benwakeford who kept this issue up to date 🙇 

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
