### ISSUE TITLE
Prevent cart from showing up

### ISSUE THREAD

**Issue by mdings** [snipcart/snipcart-v3-feedback#66]
I'm sure I read this somewhere but I'm unable to retrieve the info for now. It might have been under the V2 docs I guess.

Anyway, I'm looking for a way to stop the cart from opening (e.g. disable #cart routing) whenever a user adds an item to the cart. I'm building my own "mini-cart" UI-element which solely relies on the JS SDK but the cart popups intrusively every time I add an item to it.

What would be the best way to do this? Is there a config option that I can set (Yeajj!) or should I manually listen for changes in the routing and then prevent the route from firing when it wants to go to /#cart?

Thanks guys!

**Comment by leamarchand** [comment]
This has been added in [v3.0.12](https://docs.snipcart.com/v3/release-notes#v3012) of the cart! 
You can use `<div hidden id="snipcart" data-api-key="<API_KEY>" data-config-add-product-behavior="none"></div>` to prevent the cart from opening automatically.

See doc [here](https://docs.snipcart.com/v3/setup/cart-summary#changing-the-cart-summary-behavior)

**Comment by mdings** [comment]
Yes config option 👯 
Exactly what I was looking for, thanks!
