### ISSUE TITLE
Allow dynamic pricing with validation

### ISSUE THREAD

**Issue by mdings** [snipcart/snipcart-v3-feedback#67]
Hey I'm currently looking into integrating a tool like https://modernpricing.com/ for my e-commerce site. I was wondering if it would be possible to implement this with Snipcart as well, without reverting to "hackish" methods like creating multiple variants.

I mean, I know that you're crawling a url to validate all the prices from the cart. Could this call perhaps be allowed to be replaced by a webhook call instead, where we receive some configurable params. With those params we could then run some dynamic validation about the price strategy to follow. Or do you see other solutions to implement this?

**Comment by couellet** [comment]
We have some customers that managed to work around this by updating the data-item-url in JavaScript, they add some parameters via the query string of the URL, then use our [JSON crawler](https://docs.snipcart.com/v3/setup/order-validation#json-crawler).

You can return dynamic data based on the query string parameters from the URL.

We even wrote an article a while ago that shows how to do it, it's with the v2, but the same approach would work with the v3 as well. You'll find the post right [here](https://snipcart.com/blog/node-js-ecommerce-koa-js-tutorial) (go to section 6.2, the donate route).

**Comment by mdings** [comment]
Aha I see, a typical case of RTFM.. Sorry for that haha! Thanks for pointing me in the right direction!
