### ISSUE TITLE
Feature Request for shipping options

### ISSUE THREAD

**Issue by jackd268** [snipcart/snipcart-v3-feedback#68]
The ability to set shipping options per domain, for example if I have multiple domains on my Account I would want to be able to setup shipping options for each domain/website.

**Comment by JeanSebTr** [comment]
Hi @jackd268,

That's something that could be achieved [using our shipping webhook](https://docs.snipcart.com/v3/webhooks/shipping) by using the items' URL to determine which shipping rules to use.
