### ISSUE TITLE
422 Unprocessable Entity after connecting Mollie

### ISSUE THREAD

**Issue by mdings** [snipcart/snipcart-v3-feedback#69]
I have successfully connected Mollie in the dashboard as a payment gateway. Now, whenever I go the cart to do a checkout I receive the error below. I've tried removing all cache and retry but no luck unfortunately. Any ideas what might be going on?

```
POST https://payment.snipcart.com/api/public/sessions 422 (Unprocessable Entity)
snipcart.js:8 Uncaught TypeError: t.indexOf is not a function
```

![CleanShot 2020-06-28 at 11 05 04](https://user-images.githubusercontent.com/1887262/85943257-44f91f00-b92f-11ea-9eee-9da350c3213a.png)

**Comment by mdings** [comment]
Nobody from Snipcart? This is kind of impeding my development and implementation..

**Comment by couellet** [comment]
Sorry @mdings , we suggest you contact our support team via the chat widget in the dashboard for issues like this. You'll get faster support there.

Can you contact us there with your website URL and we'll look into this. This isn't a generalized issue, must be something related with your account configuration.

**Comment by mdings** [comment]
> Sorry @mdings , we suggest you contact our support team via the chat widget in the dashboard for issues like this. You'll get faster support there.

I don't know what's going on but if I need to wait 36hrs between every response I give then I can expect to have my cart up and running somewhere next year I'm afraid. Not the best kind of support to be honest

**Comment by JeanSebTr** [comment]
Sorry about that @mdings. The goal of this repository is to gather feedback on the V3 of the cart, not to provide support.

We're more responsive through our official support channels.

**Comment by zeshhaan** [comment]
Hey @mdings Did you fix find a solution for this issue? If yes, can you please reach out to me? We are scheduled to launch tomorrow but unfortunately getting stuck at the issue you mentioned after I switch from test to live API. Also Snipcart team wouldn't be available during the weekend.

My twitter @zeshhan email work.zeeshan@gmail.com
Thanks in advance🙏
