### ISSUE TITLE
Same item visible multiple times in the cart

### ISSUE THREAD

**Issue by judbd** [snipcart/snipcart-v3-feedback#7]
**Describe the bug**
Same items do not stack

**To Reproduce**
1. Add 1 item to the cart
2. Change the quantity
3. Go back to shopping
4. Add the same item again
5. It's handled like a new item and not stacked to the same items

**Expected behavior**
Only the quantity of the item already present in the cart have to be incremented

**Screenshots**
![image](https://user-images.githubusercontent.com/4228245/58127763-6bba3180-7c16-11e9-86f2-f232a7ca5717.png)

**Comment by couellet** [comment]
Hey there,

Thanks for the feedback! This is actually planned in the next iteration. Should be fixed in the second relase of the beta.

**Comment by couellet** [comment]
Fixed in the most recent release! Thanks.
