### ISSUE TITLE
Truncated Order date in “My Account” listing past orders

### ISSUE THREAD

**Issue by sanketdjain** [snipcart/snipcart-v3-feedback#70]
**Integration URL**
https://tiaanstore.com

**Describe the bug**
After a customer has logged in to Snipcart, then list of past orders shows truncated date. The date today is 2020/06/30, but Snipcart is showing 2020/6/0. For order on 2020/06/29, it is showing 2020/6/2. The last day value is wrong (truncated). 

**To Reproduce**
1. Click on Show Cart
2. Sign in to Account
3. Submit an order with deferred payment 
4. Click on My Account to view past orders
5. See the truncated date

**Expected behavior**
Order Date should be accurate.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/1291796/86191909-19c42a80-bafd-11ea-8456-e0a97a4bef41.png)

**Smartphone (please complete the following information):**
 - Device: IPhone X 
 - OS: iOS 13
 - Browser: Firefox 
 - Version: latest

**Comment by thatfrankdev** [comment]
Thanks for submitting this @sanketdjain 

This has actually already been fixed and will be released in v 3.0.17. Stay tuned to [our release notes](https://docs.snipcart.com/v3/release-notes) to know when it drops!
