### ISSUE TITLE
Wrong checkout amount when a discount gets applied

### ISSUE THREAD

**Issue by estruyf** [snipcart/snipcart-v3-feedback#72]
**Integration URL**

https://pimpyourowndevice.com/

**Bug description**

When I created a discount code of € 2, which is the same price as one of our products. I saw a strange thing during the check out. When I go to my site, add one product to the cart, add the discount code. All seems to be working nicely until I filled in my address. Once the address is filled in, and the shipping gets selected. The price changes from € 0 to € 1.58. Although my shipping cost is always € 2. I have no idea where this € 1.58 is coming from.

![Screenshot 2020-07-09 at 17 39 37](https://user-images.githubusercontent.com/2900833/87066191-6ea92480-c212-11ea-8460-5dbb59a4feb2.png)

**Expected behavior**

I would expect that the checkout price would be € 0. Also when applying a higher discount like € 4. It would be nice to also subtract its cost from the shipping, although this might be a feature request.

**Desktop (please complete the following information):**
 - OS: Windows and macOS
 - Browser: Chrome, Edge, Firefox
 - Version: Latest

**Comment by JeanSebTr** [comment]
Hi @estruyf !

We'll follow up in the chat thread you opened in the merchant dashboard. This will allow us to see your account configuration directly. Those issues are rarely related to the client V3 of the cart.

**Comment by estruyf** [comment]
Thanks @JeanSebTr, wasn't sure what was the best way to report this issue. I will follow up in the merchant dashboard.
