### ISSUE TITLE
Overriding featured-payment-methods component

### ISSUE THREAD

**Issue by ProduceSinapsi** [snipcart/snipcart-v3-feedback#73]
**Integration URL**
I hope I'll able provide you soon 🚀.

**Describe the bug**
Just tying to override Snipcart Vue component. **ugly red Vue Warn in console**.
The context is a Nuxt ^2.12.2 application in Universal mode.
🤔   Despite of Vue Warn, the component is overrided as expected, the  updated component is displayed correctly.

```
[Vue warn]: Unknown custom element: <featured-payment-methods> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Snipcart> at components/management/Snipcart.vue
       <Layouts/default.vue> at layouts/default.vue
         <Root>
```
**To Reproduce**
In a ~/components/Snipcart.vue, that is imported in the default.vue, I put the magical 
```<div id="snipcart" :data-api-key="snipcartApi" hidden :data-currency="currentCurrency">```
and, as documentation suggest, I put 
```
<div id="snipcart" :data-api-key="snipcartApi" hidden :data-currency="currentCurrency">
  <featured-payment-methods>
    <div class="snipcart-featured-payment-methods">
      ...

```

**Expected behavior**
Of Course, no red ugly Vue warn ever 🤙🏻
As I explained, I can touch my updated component. Is just a warn

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Mac Os Mojave
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] 83.0.410

**Additional context**
As explained in #42 , I've to move the snipcart.js injection in nuxt.config.js but the script is not loaded properly.
But this is another issue.

``` 
 script: [
      // {
      //   src: 'https://cdn.snipcart.com/themes/v3.0.17/default/snipcart.js',
      //   body: true,
      //   async: false
      // } 
    ]
```

**Comment by thatfrankdev** [comment]
Hi @ProduceSinapsi 

So sorry we couldn't respond to this one sooner. I hope you were able to get support from us via your merchant dashboard or via email.

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need still need support here, or if you want to submit feedback, please reach out to support@snipcart.com.

Thanks
