### ISSUE TITLE
How to modify Payment form css

### ISSUE THREAD

**Issue by ebhoren** [snipcart/snipcart-v3-feedback#75]
I looking for a way to customize css included in the payment form. 
From what i'm seeing, payment form is included in a iframe and there is no way to inject custom css into due to sandbox security. Is there documentation about this limitation?

**Screenshots**
![payment](https://user-images.githubusercontent.com/613562/87767785-2927c100-c7e9-11ea-9ab1-148fad8ee920.jpg)

Thanks

**Comment by thatfrankdev** [comment]
Hi @ebhoren 

So sorry we couldn't respond to this one sooner.

Customizing the payment form CSS was not possible, until this week's release! Stay tuned to [our release notes](https://docs.snipcart.com/v3/release-notes) to know when it drops.

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com.

Thanks
