### ISSUE TITLE
Documentation for Dashboard template

### ISSUE THREAD

**Issue by ebhoren** [snipcart/snipcart-v3-feedback#76]
It would be nice to have some documentation about the <dashboard> template. Currently, it's almost impossible to customize it's layout without any kind of documentation.

Thanks

**Comment by thatfrankdev** [comment]
Hi @ebhoren

So sorry we couldn't respond to this one sooner. Most overridable templates are listed on [this page](https://docs.snipcart.com/v3/themes/default/reference), but clearly, it lacks searchability and organization. That's something we plan to improve in the future.

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com.

Thanks
