### ISSUE TITLE
Documentation for Sign In & Log In template

### ISSUE THREAD

**Issue by ebhoren** [snipcart/snipcart-v3-feedback#77]
It would be nice to have some documentation about these templates. Currently, it's almost impossible to customize their layouts without any kind of documentation.

Thanks

**Comment by thatfrankdev** [comment]
Hi @ebhoren 

So sorry we couldn't respond to this one sooner. Most overridable templates are listed on [this page](https://docs.snipcart.com/v3/themes/default/reference), but clearly, it lacks searchability and organization. That's something we plan to improve in the future.

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com.

Thanks
