### ISSUE TITLE
Error in Sdk Events documentation

### ISSUE THREAD

**Issue by filippolcr** [snipcart/snipcart-v3-feedback#78]
**Integration URL**
If you can, provide an URL where we can see your Snipcart integration.
[https://docs.snipcart.com/v3/sdk/events](https://docs.snipcart.com/v3/sdk/events)

**Feedback**
snipcart.initialization.error example code is wrong.

`Snipcart.events.on('snipcart.initialized', () => {
    console.log('Failed to initialize Snipcart');
});`

**Comment by thatfrankdev** [comment]
Hi @filippolcr,

Thanks so much for taking the time to report this, and sorry we couldn't respond sooner. I just fixed the event name typo in this code block.

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com.
