### ISSUE TITLE
 Order history not work with Nuxt

### ISSUE THREAD

**Issue by filippolcr** [snipcart/snipcart-v3-feedback#79]
**Integration URL**
https://app.snipcart.com/invoice/**uniq-id-of-invoice**

**Describe the bug**
Clicking on **Click here to view the order history** link (at the bottom) open the following link:

> my-domani/#!/history/xxxxx-xxxxx-x-xxxxxx

The page loads, but after a few seconds the url becomes my-domain again (/#!/history/xxxxx-xxxxx-x-xxxxxx erased). 
Much like a redirect.

**To Reproduce**
Open an invoice at address https://app.snipcart.com/invoice/**uniq-id-of-invoice**

**Expected behavior**
Load the order history

Using Nuxt 2.14

**Comment by thatfrankdev** [comment]
Hi @filippolcr 

So sorry we couldn't respond to this one sooner. I've just validated, and this is still a bug we have when generating invoices. It has been documented in our product backlog.

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com.

Thanks
