### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by judbd** [snipcart/snipcart-v3-feedback#8]
As in V2, it will be great if the multinlingual based on the html locale were supported.

**Comment by JeanSebTr** [comment]
Hi @judbd !

Localization is backed in, but we've only provided an English translation for now.

We'll document that soon!

**Comment by judbd** [comment]
Great! It will be cool if it is based on the html lang attribute like now, but I can also inject a locale somewhere.

**Comment by erikgeelhuijzen** [comment]
Hi, testing the non-beta 3.0 version (congrats on your achievement!), using lang="nl" in the head, but the cart-language is still english. What am I doing wrong?

**Comment by Unbel** [comment]
i can't do it too

**Comment by JeanSebTr** [comment]
Hi everyone!

We released [multilingual support](https://docs.snipcart.com/v3/setup/localization) in 3.0.4 and completed support in the payment form in 3.0.5!
https://docs.snipcart.com/v3/release-notes
