### ISSUE TITLE
Problem with nuxt-18n module

### ISSUE THREAD

**Issue by filippolcr** [snipcart/snipcart-v3-feedback#80]
I'm using nuxt-i18n module with two locale (EN/IT).
IT locale is the default so, e.g. homepage is my-domain/ and EN is my-domain/en

When I click on e.g. Log In Snipcart add /#/signin to the route.

But if I'm on my-domain/en, when hit the route /#/signin, Snipcart remove the /en part and reload the page as my-domain/#/signin with IT locale.

Another thing that I've noticed is that when I'm on /en route and click on snipcart-checkout Snipcart add my-domain/en#/cart

So, it's clear that I've to provided trailingSlashes for localized routes. But this is a sensitive issue in Nuxt.

Can you provide me any advice based on your experience with nuxt that can put me on track?

if you need other information I am at your disposal.

Thanks 🙏

**Comment by thatfrankdev** [comment]
Hi @filippolcr 

So sorry we couldn't respond to this one sooner.

Thanks for reporting this conflictual behavior of our cart's routing with nuxt-i18n module. I'll have it documented as a bug in our product backlog.

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you still need support or if you want to submit feedback, please reach out to support@snipcart.com.

Thanks
