### ISSUE TITLE
Add to Cart not working

### ISSUE THREAD

**Issue by fowlerat** [snipcart/snipcart-v3-feedback#83]
**Integration URL**
https://ccpdev-f.co.uk/products-technologies/fire-monkey

**Describe the bug**
Console shows a call to 'GET https://cdn.snipcart.com/themes/v3.0.20/l10n/en_US.json' which doesn't exist. Seems to fall back to en.json but then has a number of fails due to incorrect locale.

**To Reproduce**
You have to click on Add to Cart twice - this is error 1. Then cart get stucks with 'preparing your cart error' error 2.

**Comment by fowlerat** [comment]
Resolved - You have to have html lang set as en. If you use something like en_US then the code fails.

**Comment by JeanSebTr** [comment]
I've reopened this. The cart should fallback to "region-less" locale and not cause any issue except for console errors.

We'll try to reproduce.

**Comment by thatfrankdev** [comment]
Hi @fowlerat 

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

This issue has been documented in our product backlog. If you need any support or if you want to submit feedback, please reach out to support@snipcart.com.

Thanks
