### ISSUE TITLE
Business Name in Billing and Shipping?

### ISSUE THREAD

**Issue by handplant** [snipcart/snipcart-v3-feedback#84]
How do I get the Business Name in Customers Billing and Shipping with Custom Order Fields as shown in the screenshot?

![Bildschirmfoto 2020-09-09 um 12 12 30](https://user-images.githubusercontent.com/2598962/92586076-1637e700-f296-11ea-8494-f5f041de2c35.png)

**Comment by thatfrankdev** [comment]
Hi @handplant 

So sorry we couldn't respond to this one sooner. I hope you were able to get support from us via your merchant dashboard or via email.

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If not done already, please reach out to us at support@snipcart.com and paste the link to this issue in your email so we can follow up regarding this.

Thanks
