### ISSUE TITLE
Expose l10n locale strings in Javascript API

### ISSUE THREAD

**Issue by ebhoren** [snipcart/snipcart-v3-feedback#86]
It would be awesome if you could expose the l10n locale string in Snipcart Javascript API. That way, we could use it outside of Snipcart VueJS context. As an example, i'm working on a notification popup that appear when user add an item to cart. Inside that popup, i need to access some locales that are part of https://github.com/snipcart/snipcart-l10n

One way to expose these strings could be: Snipcart.api.l10n.getLocale('string-id');

Thanks

**Comment by thatfrankdev** [comment]
Hi @ebhoren,

Thanks for this suggestion. It makes a lot of sense. I'll have it added to our product roadmap and we'll get to it eventually. Can't commit on an ETA at the moment though.

**Comment by thatfrankdev** [comment]
Hi @ebhoren 

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com.

Thanks
