### ISSUE TITLE
Invalid label[for] and missing input[id] attributes when using multi-word custom fields

### ISSUE THREAD

**Issue by bluematt** [snipcart/snipcart-v3-feedback#87]
**Describe the bug**
When using a multi-word custom field (e.g. "Custom message") this yields two related issues:

1. the `label`'s `for` attribute reflects the name of the custom field, i.e. `<label for="Custom message">` rather than a valid `id`.
2. the related `input`/`textarea`/`select` input does not have an `id` attribute.

**To Reproduce**
```html
<button class="snipcart-add-item"
  data-item-id="item-id"
  data-item-price="9.99"
  data-item-url="https://url/to/item"
  data-item-description="Item description"
  data-item-name="Item name"
  data-item-custom1-name="Custom message"
  data-item-custom1-type="textarea"
  data-item-custom1-placeholder="Enter your custom message">Add to cart</button>
```

Generates (within the cart - formatted for clarity):
```html
<div class="snipcart-item-custom-fields__field snipcart-item-custom-fields--textarea">
  <label for="Custom message" class="snipcart-form__label snipcart__font--tiny snipcart-custom-field-wrapper__label"> Custom message
    <!---->
  </label>
  <div class="snipcart-custom-field-wrapper__input snipcart__font--secondary snipcart__font--std">
    <textarea name="Custom message" placeholder="Enter your custom message" class="snipcart-textarea snipcart__font--secondary snipcart__font--bold snipcart-input snipcart-textarea-custom-field"></textarea>
    <!---->
  </div>
</div>
```

**Expected behavior**
I would expect to see valid ids for the `for` and `id` attributes on the respective `label` and `textarea` elements:

```html
<div class="snipcart-item-custom-fields__field snipcart-item-custom-fields--textarea">
  <label for="Custom_message" class="snipcart-form__label snipcart__font--tiny snipcart-custom-field-wrapper__label"> Custom message
    <!---->
  </label>
  <div class="snipcart-custom-field-wrapper__input snipcart__font--secondary snipcart__font--std">
    <textarea id="Custom_message" name="Custom message" placeholder="Enter your custom message" class="snipcart-textarea snipcart__font--secondary snipcart__font--bold snipcart-input snipcart-textarea-custom-field"></textarea>
    <!---->
  </div>
</div>
```

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser: Chrome 
 - Version: 85.0.4183.102 (Official Build)

**Comment by leamarchand** [comment]
Thanks for pointing that out! This issue has been added to our backlog.

**Comment by thatfrankdev** [comment]
Hi @bluematt 

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If not done already, please reach out to us at support@snipcart.com and paste the link to this issue in your email so we can follow up once the issue is resolved.

Thanks
