### ISSUE TITLE
POST /products results in 401 (Unauthorized)

### ISSUE THREAD

**Issue by mdings** [snipcart/snipcart-v3-feedback#88]
I'm using a cURL command to post to the endpoint mentioned in the issue subject. I'm getting an Unauthorized result back not matter what. I'm suspecting a bug here but I have no tracelogs.

```curl
  curl https://app.snipcart.com/api/products
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -U "MY_PRIVATE_APIKEY_FROM_SETTINGS" \
    -d "{fetchUrl: 'https://www.jack-hunt.com/api/product-feed.json'}"
```

**Comment by JeanSebTr** [comment]
Make sure to format your json with double quotes:

`{"fetchUrl":"https://www.jack-hunt.com/api/product-feed.json"}`

Did you try the curl command we recommend [in the doc](https://docs.snipcart.com/v3/api-reference/authentication#example-request-bash): (lower `-u` and appending `:` to the API key)

```sh
curl https://app.snipcart.com/api/products
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -u "MY_PRIVATE_APIKEY_FROM_SETTINGS:" \
    -d '{"fetchUrl": "https://www.jack-hunt.com/api/product-feed.json"}'
```

**Comment by mdings** [comment]
Hey @JeanSebTr,

Yes I tried that just now and still the same 401 Unauthorized error.

**Comment by JeanSebTr** [comment]
Can you write to geeks@snipcart.com and linking to this thread, we'll have a look.

As long as you're using the secret API keys and not the public one, the call shouldn't return a 401.
