### ISSUE TITLE
Update stock with POST /products

### ISSUE THREAD

**Issue by mdings** [snipcart/snipcart-v3-feedback#89]
I want to build a cron job that should synchronize my inventory from an external system every night. It would be nice if I can update this in a single batch by using the `{inventoryManagementMethod: single}` together with the `{stock: amount}` prop. I don't see this currently being supported reading the documentation. It is however supported on PUT /product, but that would require me to update all my products individually.

Any thoughts?

Regards

**Comment by JeanSebTr** [comment]
Hi @mdings !

The same JSON structure from [`PUT /products/{id}`](https://docs.snipcart.com/v3/api-reference/products#put-productsid) can be returned from the URL you send to `POST /products`. This will allow you to keep all your inventory up to date in a single query.
