### ISSUE TITLE
Change quantity with number field in cart

### ISSUE THREAD

**Issue by judbd** [snipcart/snipcart-v3-feedback#9]
Like in V2, the quantity can only be incremented with +/-, 1 increment at a time, and it's really slow because there is some halt time between 2 clicks.

An editable quantity number field will be great.

**Comment by couellet** [comment]
We plan to improve the performance of the + / - with some "debouncing". This will probably be the first step here.

**Comment by thatfrankdev** [comment]
Hi there,

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
