### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by hotdoy** [snipcart/snipcart-v3-feedback#90]
**Integration URL**
https://wheat.calotte.ca/fr/

**Describe the bug**
When a user is connected, and viewing past orders, the "View Invoice" is not affected by the user locale.

**To Reproduce**
- Open cart
- Create and/or connect to user account
- Check past order

**Screenshots**
![account-invoice](https://user-images.githubusercontent.com/11572524/94991891-3173da80-0554-11eb-9f10-506d12cf9779.jpg)

**Additional context**
Big shout out on the V3. Snipcart is great again.
Are you guys planning any surprise on the seller dashboard as well?

👋

**Comment by hotdoy** [comment]
Oh I forgot to mention. I did test other languages as well just to be sure it's not something with the FR translation.

**Comment by thatfrankdev** [comment]
Thanks for reporting this @hotdoy. We'll have it added in the next release. In the meantime, you can override the `customer_dashboard.view_invoice` key using the JavaScript SDK: https://docs.snipcart.com/v3/setup/localization#using-our-javascript-api

Know that you can always contribute to add missing keys by opening a Pull Request in this repository: https://github.com/snipcart/snipcart-l10n

Cheers! 👍
