### ISSUE TITLE
Test Payment Not working

### ISSUE THREAD

**Issue by sadiqueamt** [snipcart/snipcart-v3-feedback#91]
Hi,

I couldn't complete the test payment, it's showing 'Unable to process your payment
Please review your card details, or try again later.'

Thanks.

![image](https://user-images.githubusercontent.com/63390769/95329097-0e368b80-08c4-11eb-8630-afa7ac782237.png)

**Comment by thatfrankdev** [comment]
Hi @sadiqueamt, It appears you are testing on localhost. Although it works for the most part of the checkout, the final order processing cannot be performed if your site is not hosted publicly. See this docs entry for more details: https://docs.snipcart.com/v3/setup/order-validation

Also make sure you are using our Test API key.

**Comment by sadiqueamt** [comment]
Thanks.
