### ISSUE TITLE
CustomFields are blanked after proceeding to payment

### ISSUE THREAD

**Issue by marekszewczyk1988** [snipcart/snipcart-v3-feedback#92]
**Describe the bug**
When customField is setup in a shipping step e.g.:

```  
updateCustomShippingInfo: async shippingInfo => {
    try {
      const customFields = (await snipcartUtil.getSession()).cart.customFields.filter(field => field.name !== "shippingInfo") || [];
      customFields.push({
        name: "shippingInfo",
        required: false,
        value: shippingInfo,
      });
      await Snipcart.api.cart.update({
        customFields: customFields
      })
    } catch (error) {
      console.log(error)
    }
  },
```
Then it disappears when proceeding to payment step.

**To Reproduce**
1. Add any item to your cart
2. Go to checkout
3. Fill billing and go to shipping
4. Add customField programatically
5. Proceed to payment
6. customField is empty

**Expected behavior**
6. CustomField from step 5 still exists

**Additional context**
Snipcart 3.0.22

**Comment by thatfrankdev** [comment]
Thanks for reporting this. It's definitely a bug that appeared in version 3.0.20. We'll have a fix planned for it. 🙇

**Comment by marekszewczyk1988** [comment]
@thatfrankdev Do you have any ETA? I see that new version was released few days ago (v3.0.23) but the bug is still there?

**Comment by thatfrankdev** [comment]
@marekszewczyk1988 Can't give a precise ETA at the moment. It's been added to the roadmap. In the meantime, installing to 3.0.19 will prevent the issue from happening.

**Comment by thatfrankdev** [comment]
Hi @marekszewczyk1988 

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If not done already, please reach out to us at support@snipcart.com and paste the link to this issue in your email so we can follow up on the matter once the issue gets fixed (it's planned to be worked on soon).

Thanks
