### ISSUE TITLE
500 Network Error Using Webhooks (Shipping Rates)

### ISSUE THREAD

**Issue by mcfarlanedev** [snipcart/snipcart-v3-feedback#93]
**Integration URL**
https://www.saorsajewelry.com

Add a product to the shopping cart

**Describe the bug**
When I have added an item to the shopping cart and proceed to the checkout, I see a loading spinner that fails to resolve. Upon closer inspection, the browser dev tools reports a 500 response from Snipcart in the Network pane, and a Snipcart console error in the Console pane. 

**To Reproduce**
1. Go to [https://www.saorsajewelry.com/category/rings/amethyst-ring-stainless-steel#/cart](https://www.saorsajewelry.com/category/rings/amethyst-ring-stainless-steel#/cart)
2. Click on 'Checkout'
3. Billing: Add an example billing/shipping address e.g 47 West 13th Street and let AutoComplete fill in the rest.
4. Click 'Continue To Shipping'
5. The loading spinner persists on the Continue To Payment button

**Expected behavior**
I would have expected Snipcart to display information about the shipping rate upon clicking Continue To Shipping in the Shipping pane. 

**Screenshots**
Loading Spinner
![image](https://user-images.githubusercontent.com/12474833/95495286-1ca1a780-0997-11eb-9763-27c082093c57.png)

Console Error
![image](https://user-images.githubusercontent.com/12474833/95495359-38a54900-0997-11eb-972c-7fdaa55cc735.png)

Network Error
![image](https://user-images.githubusercontent.com/12474833/95495485-68545100-0997-11eb-9bfc-f966672f374c.png)

**Desktop (please complete the following information):**
 - OS: Pop!OS 20.04
 - Browser: Brave 
 - Version 1.14.84

**Additional context**
Snipcart V3.0.22
I am using a custom webhook to calculate the shipping rate based on the cart's currency. I have the following values set:

**https://app.snipcart.com/dashboard/webhooks**
![image](https://user-images.githubusercontent.com/12474833/95498668-1104af80-099c-11eb-87b6-ce12bdfb4aef.png)

**https://app.snipcart.com/dashboard/carriers/webhooks**: 
![image](https://user-images.githubusercontent.com/12474833/95498584-f5010e00-099b-11eb-814c-a4df8e0b8a31.png)

The server I host to provide the shipping rates is not being called by Snipcart.

**Comment by leamarchand** [comment]
Could you contact us via the chat widget of the dashboard or via email at support@snipcart.com with the link to this issue. 

Cheers

**Comment by mcfarlanedev** [comment]
Hello!

@leamarchand Happy to tell you that this seems to be working now. Not sure what changed, but no longer facing any of those errors I had reported anymore. 🎉

![image](https://user-images.githubusercontent.com/12474833/95661366-9ae08400-0b26-11eb-8d6a-8e5b78bef039.png)

**Comment by couellet** [comment]
Thanks for letting us know!
