### ISSUE TITLE
Webhook failing on no Post method

### ISSUE THREAD

**Issue by mdings** [snipcart/snipcart-v3-feedback#94]
Since I've switched to live mode I noticed that my webhooks are failing that used to be working in test mode. 
The error log inside the dashboard is displaying `Unrecognized HTTP Method, only POST allowed` which is the bail-out for any non-post methods according to the function that is being called as per code below. Any idea why this is happening?

```javascript
const sanityClient = require('@sanity/client')

const client = sanityClient({
    projectId: process.env.SANITY_PROJECT_ID,
    dataset: 'production',
    token: process.env.SANITY_WRITE_TOKEN,
    useCdn: false
})

exports.handler = async (event, context) => {
    
    if (event.httpMethod != 'POST') {
        return {
            statusCode: 400,
            body: 'Unrecognized HTTP Method, only POST allowed'
        }
    }

    const payload = JSON.parse(event.body)

    if (payload && payload.eventName == 'order.completed') {
        const { items } = payload.content
        const promiseResolver = []
        items.forEach(item => {
            promiseResolver.push(client
                .patch(item.id)
                .inc({sold: item.quantity})
                .commit()
            )
            promiseResolver.push(client
                .patch(item.id)
                .dec({stock: item.quantity})
                .commit()
            )
        })

        const resolve = await Promise.all(promiseResolver)
        
        return {
            statusCode: 200,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify('ok')
        }
    }
}
```

**Comment by couellet** [comment]
@mdings all incoming Webhooks are POST requests. Can you let us know what is the Webhooks URL you have configured? You can contact us at geeks@snipcart.com if you prefer.

**Comment by mdings** [comment]
I've sent the webhook url through email, thanks!

**Comment by thatfrankdev** [comment]
@mdings I believe this case has already been resolved. Am I correct?

Please let me know

**Comment by thatfrankdev** [comment]
@mdings We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If not done already, please reach out to us at support@snipcart.com and paste the link to this issue in your email so we can follow up on the matter.

Thanks

**Comment by mdings** [comment]
Yep, resolved. Can be closed!
