### ISSUE TITLE
Rounding issues with VAT and discount codes

### ISSUE THREAD

**Issue by estruyf** [snipcart/snipcart-v3-feedback#95]
There are rounding issues in the system when using discounts and VAT. This issue leads to situations where the customer has to pay € 0.01. Already getting complaints about this:

![Screenshot 2020-10-21 at 09 56 54](https://user-images.githubusercontent.com/2900833/96690371-e47d6a00-1383-11eb-8e28-47cbb0355307.png)

I provided two discount codes (as the system cannot do a combination of fixed amount + free shipping). The discount is set to € 6.62 (Excl. VAT).

When the user checks out, the total amount is € 6.60 - which should actually be € 6.61, and hereby the **tax adjustments** is incorrect. I hope this issue gets fixed soon as 200 of these orders are on the way.

**Comment by thatfrankdev** [comment]
Thanks for the detailed report @estruyf. We'll have a look at this particular scenario, there obviously is a problem here 🙇

**Comment by estruyf** [comment]
Hopefully, these invoices can be corrected on your end as well.

**Comment by leamarchand** [comment]
@estruyf Hey, just letting you know that a fix has been deployed! Cheers

**Comment by thatfrankdev** [comment]
@estruyf Don't hesitate to follow up at support@snipcart.com if you need our help on anything.
