### ISSUE TITLE
ShippingAddress info is required even when all the products in the cart are digital products (= not shippable)

### ISSUE THREAD

**Issue by neuronkun** [snipcart/snipcart-v3-feedback#96]
**Describe the bug**
- ShippingAddress info is required to move on to the payment section even when all the products in the cart are defined as digital products(=non-shippable).
- Snipcart understands it (given the fact that shipping section is omitted) and the UI works correctly,  but the backend requires to provide with ShippingAddress info, which is contradicting.
- I coded the related attributes like below. (I'm using React.)

```
data-item-shippable={false}
data-item-file-guid={'a-valid-guid'}
```

**Expected behavior**
- Users can move on to the payment section without being required to do anything with ShippingAddress info when all the products in the cart are non-shippable.

**Screenshots**
![Frame 1](https://user-images.githubusercontent.com/32223981/97293627-48c29100-1890-11eb-88df-995dab456870.png)

**Additional context**
Thank you!

**Comment by thatfrankdev** [comment]
Thanks for reporting @neuronkun. Just to make sure we get the full picture here:

- Please confirm the markup of the buy button has the data-attribute set as follows once it is rendered: `data-item-shippable="false"`
- Are you using Snipcart JavaScript SDK to edit your cart in some way?
- Is the issue happening with a fresh session as well? (with cookies cleared)

A link to your live site might help us as well.

Please let me know, as it will help in diagnosing this and better isolate the bug.

Thanks!

**Comment by thatfrankdev** [comment]
Quick follow up here @neuronkun. Did you end up getting this working? If not, please give us the info requested above ☝️ 

Thanks

**Comment by thatfrankdev** [comment]
@neuronkun We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If not done already, please reach out to us at support@snipcart.com and paste the link to this issue in your email so we can follow up on the matter.

Thanks
