### ISSUE TITLE
Cart modification during payment session

### ISSUE THREAD

**Issue by marekszewczyk1988** [snipcart/snipcart-v3-feedback#97]
I use mollie as a payment gateway, but I suppose the bug occurs at all payment gateways. 
The final order is placed based on the current cart data, instead of the cart in payment session. It is very dangerous because order may contain more items than it was paid for 

**To Reproduce**
1. Add 1 item to the cart
2. Go to checkout, choose pay by mollie
3. In the concurrent browser tab add another item to the cart
4. Finalize your payment in mollie gateway
5. Be redirected to order confirmation page.

**Actual behavior**
6. Order contains 2 items, order paid for 1 item

**Expected behavior**
6. Order contains only 1 item, order paid for 1 item

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.2
 - Browser Chrome Version 86.0.4240.111 (Official Build) (64-bit)
 - Snipcart version 3.0.23

**Additional context**
Final order should be created based on payment session data.

**Comment by couellet** [comment]
Thanks for the details. That's indeed a serious problem. We'll prioritize a fix for this.

**Comment by thatfrankdev** [comment]
Hi @marekszewczyk1988 and thanks for reporting this.

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If not done already, please reach out to us at support@snipcart.com and paste the link to this issue in your email so we can follow up on the matter.

Thanks
