### ISSUE TITLE
Provide giftwrap option

### ISSUE THREAD

**Issue by mdings** [snipcart/snipcart-v3-feedback#98]
Is it possible to add an optional feature to gift wrap a product during checkout? This should lead to an upsell with a specified amount.

Perhaps this is already possible using [customization](https://docs.snipcart.com/v3/setup/customization) but not sure how to approach that. Any pointers would be helpful!

**Comment by mdings** [comment]
Anyone? 😀

**Comment by mdings** [comment]
I got this figured out by overriding the cart component as following:

```html
<div class="snipcart-cart__giftwrap" v-if="Snipcart.checkGiftwrap()">
  <div class="snipcart-item-line__container">
    <h2 class="snipcart__font--xlarge snipcart__font--secondary snipcart__font--black">Holidays coming up, let Jack gift wrap your presents!</h2>
    <p class="snipcart__font--std">
    You can choose to have your items in the cart gift wrapped personally by Jack. <br />All items will by wrapped individually with a sturdy and eco-friendly wrapping paper.
    </p>
    <span @click="Snipcart.addGiftwrap" class="snipcart__font--bold snipcart__font--secondary snipcart__font--large snipcart__cta">Please add some wrapping for only &euro;{{Snipcart.latestPriceFromSettings}}!</span>
    </div>
  </div>
</div>
```

Would you see this is the right way to do this. I'm using an external json feed to validate the products so the giftwrap option also needs to be added there. That is not ideal but I don't know how else to approach this.

Is there a way to make the line items appear in a certain order? I always want the gift wrap option to appear last.

**Comment by thatfrankdev** [comment]
Hi @mdings 

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If not done already, please reach out to us at support@snipcart.com and paste the link to this issue in your email so we can follow up on the matter.

Thanks

**Comment by mdings** [comment]
Hi @thatfrankdev,

Do you offer something like a Slack-channel or otherwise community related channels? Where do users from Snipcart turn to with these kind of questions?
That's really something this is lacking imho. I mean, this feedback-related questions gets closed without any noteworthy input from Snipcart's side..

**Comment by thatfrankdev** [comment]
@mdings At the moment we do not have that kind of support channel, and we're totally aware that it's a missing piece for us and our users. Not clear exactly when, but we plan to roll out a public Discourse forum in 2021, and restructure our support efforts around it.

Until we put that together, our only support channels will be email and the chat box in Snipcart merchant dashboard.

Thanks for your comprehension

**Comment by thatfrankdev** [comment]
@mdings 
> That's really something this is lacking imho. I mean, this feedback-related questions gets closed without any noteworthy input from Snipcart's side.

To be clear, I'm not saying we won't answer the questions you have. I'm saying we will answer them via email rather than here. 👍
