### ISSUE TITLE
Custom Checkboxes not work correctly

### ISSUE THREAD

**Issue by filippolcr** [snipcart/snipcart-v3-feedback#99]
https://www.producesinapsi.com/masks

When I add 2 products to the cart and select a checkbox for the second product, the checkbox corresponding to the first is triggered.

```
<button
  class="snipcart-add-item ps-grid-item-btn"
  :data-item-id="mask.sys.id"
  :data-item-url="getItemUrl"
  :data-item-description="mask.fields.description"
  :data-item-image="getImageFront(mask)"
  :data-item-name="mask.fields.name"
  :data-item-weight="mask.fields.weight"
  :data-item-price="getPrice(mask)"
  :data-item-has-taxes-included="false"
  :data-item-custom1-name="$t('snipcart.logo')"
  data-item-custom1-type="checkbox"
  :data-item-custom2-name="$t('snipcart.gift')"
  data-item-custom2-type="checkbox"
  :data-item-custom3-name="$t('snipcart.message')"
  data-item-custom3-type="textarea">
     {{ $t('productMask.addToCart') }}
</button>
```

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome, Safari, Firefox
 - Last versions

**Smartphone (please complete the following information):**
- Not tested

**Comment by thatfrankdev** [comment]
Thanks for reporting this @filippolcr 

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

If not done already, please reach out to us at support@snipcart.com and paste the link to this issue in your email so we can follow up on the matter.

Thanks
